# src/judgemetrics/metrics/methodology.py
"""Render ``docs/METHODOLOGY.md`` from the metric registry.

The committed document is a snapshot of ``render_methodology()`` the way
``docs/openapi.json`` is a snapshot of the OpenAPI document:
``judgemetrics methodology render`` writes it, ``--check`` (and the unit
test) fails when the file differs, so a registry change reaches the
methodology page in the same pull request. The text is wrapped at 80
columns; the brief's statistical warnings are rendered verbatim,
unsoftened, as the "Known limitations" list. A relative output path is
resolved under the repository root, never the working directory.

Methodology 1.1 (Phase 5 Step 5) adds sections rendered from the registry's
``periods`` and ``revocation_scopes``, from every registered connector's
``SourceInfo`` ("Source limitations": its capabilities, observable outcomes,
and notes), from ``metrics.coverage.DEFINITIONS`` ("Coverage statistics"),
from the specification's ``availability``, and from the registry's threshold
rationale and measured cohorts. ``GET /api/v1/metrics`` keeps serving the
constants it served (``HOW_TO_READ``, ``SEMANTICS``, ``ATTRIBUTION_TEXT``,
``GATE_TEXT``, ``CHANGELOG``, ``adjustment_prose``); the new sections reach the
API with Phase 5 Step 7.
"""

from __future__ import annotations

import difflib
import textwrap
from collections.abc import Iterable
from dataclasses import dataclass
from pathlib import Path

from judgemetrics.config import REPO_ROOT
from judgemetrics.metrics.adjustment.spec import (
    DECISION_AT,
    EXCLUDE,
    FILED_AT,
    INDEX_AT,
    UNSEEN_LATEST,
    FeatureSpec,
    OutcomeModelSpec,
    load_spec,
)
from judgemetrics.metrics.registry import (
    WINDOWS_DAYS,
    MetricDefinitionSpec,
    Registry,
    load_registry,
)

DEFAULT_OUTPUT = Path("docs") / "METHODOLOGY.md"
WIDTH = 80
PATH_COMMENT = "<!-- docs/METHODOLOGY.md -->"
GENERATED_NOTICE = (
    "<!-- Generated by `judgemetrics methodology render` from\n"
    "     data/reference/metric_registry.yaml. Do not edit by hand: change the\n"
    "     registry and re-render. -->"
)

GATE_TEXT: dict[str, str] = {
    "deciding_judge": "the deciding judge (the decision's judge is the subject)",
    "assigned_at_time": (
        "the judge assigned at the event time (the time falls in one of the "
        "judge's assignment intervals on the case, start <= t < end, an open end "
        "unbounded)"
    ),
    "assigned_ever": "any judge with at least one assignment on the case",
    "sentencing_judge": "the sentencing judge (the sentence's judge is the subject)",
    "disposing_judge": (
        "the disposing judge (the judge the source records as entering the charge's "
        "disposition; for a case, the judge on the charge whose disposal sets the case "
        "disposition time, ties broken by the source's charge id)"
    ),
    "court_of_case": "the court of the case (a court-only metric)",
}
KIND_TEXT: dict[str, str] = {
    "count": "count",
    "share": "share (numerator over denominator, Wilson interval)",
    "windowed_rate": "fixed-window rate per observation window (Wilson interval)",
    "survival": "Kaplan-Meier cumulative incidence per observation window",
    "distribution": "distribution of counts by dimension value",
    "median": "median",
    "observed_expected": (
        "observed-to-expected ratio, partially pooled (gamma-Poisson), with a "
        "person-cluster bootstrap percentile interval"
    ),
}

HOW_TO_READ: tuple[tuple[str, str], ...] = (
    (
        "Numerator",
        "the count of rows or members that met the metric's condition, stated beside every number.",
    ),
    (
        "Denominator",
        "the count the numerator is divided by: the attributed rows for a "
        "share, the followed cohort members for a fixed-window rate, the "
        "whole cohort for a survival estimate, the values a median is taken "
        "over. A count has no denominator.",
    ),
    (
        "Date range",
        "the period the observation covers: the source's whole coverage window, "
        "or one calendar year of it (period_start to period_end), the dates "
        "within which every counted row's anchor falls.",
    ),
    (
        "Coverage",
        "the source the rows come from, its coverage window, and the snapshot "
        "(a content hash of the exported tables) the number was computed "
        "from, so it can be reproduced later.",
    ),
    (
        "Sample size",
        "the eligible count (the whole cohort before any follow-up "
        "restriction) and the cohort size (the denominator). The eligible "
        "count is published even when the number itself is suppressed; the "
        "denominator is withheld with the number.",
    ),
    (
        "Interval",
        "a 95% Wilson score interval for every share and fixed-window rate, "
        "a Greenwood interval for every Kaplan-Meier estimate. An adjusted "
        "statistic (an observed-to-expected ratio) carries a 95% percentile "
        "interval from a person-cluster bootstrap with the model refitted "
        "per replicate, and its methodology version: the interval describes "
        "the sampling variability of the pooled estimate, not a confidence "
        "interval for the judge's true ratio (Adjusted statistics).",
    ),
    (
        "Suppression",
        "a number whose denominator is below the metric's suppression "
        "threshold is withheld and marked suppressed — the numerator, "
        "denominator, value, distribution, and interval leave the API as "
        "null and the threshold is stated per metric below and beside every "
        "observation.",
    ),
    (
        "Versions",
        "every observation records the registry version, the methodology "
        "version, the code version, and the snapshot it was computed under.",
    ),
)

SEMANTICS: tuple[tuple[str, str], ...] = (
    (
        "Index events",
        "An index event is one person, one case, one kind, and one instant "
        "(index_at): the moment follow-up is measured from. Three kinds exist. "
        "pretrial_release: an attributed pretrial decision (the metric's "
        "attribution rule applies) with detained = false and a release time; "
        "the index time is the release time. disposition: a disposed case - "
        "one with a charge whose disposition is final (dismissed, acquitted, "
        "or a conviction; never pending, superseded, or transferred) and dated "
        "- at the case disposition time, the latest disposed_at among its "
        "disposed charges, attributed to the case's disposing judge, the judge "
        "on the charge whose disposal sets that time; one index event per "
        "person with a disposed charge in the case. sentence: an attributed "
        "sentencing decision at sentence_at, attributed to the sentencing "
        "judge. A court's index events are those of the court's cases. An index "
        "event the source dates outside its coverage window is no cohort "
        "member.",
    ),
    (
        "Exposure",
        "Time at risk starts at the index time and is deferred by "
        "incarceration, because a person who is incarcerated cannot accrue a "
        "new case in the community. An incarceration term is [sentence_at, "
        "sentence_at + incarceration_days) of a sentence with a positive "
        "incarceration_days. For the disposition kind the start first moves "
        "to the end of the index case's own term (the sentence of the same "
        "case and person, the latest term end when there are several), "
        "because the sentence follows the disposition; when a source dates "
        "that term to end at or before the disposition, the start stays at the "
        "index time. Then, for every kind - "
        "pretrial_release included - while a term of the same person in any "
        "case contains the start, the start moves to the end of the "
        "containing term that ends last, so exposure begins at the first "
        "instant at or after the index time that no recorded term of the "
        "person covers; for the sentence kind the member's own term is the "
        "first. Documented limitation: only terms the source records are "
        "applied - a term served in another jurisdiction, or under a sentence "
        "the source does not publish, is not modelled, so time at risk is "
        "overstated for such persons and their rates are biased downward.",
    ),
    (
        "Outcomes and windows",
        "An outcome counts for a window w when an event of the outcome type "
        "occurs in (exposure start, exposure start + w days]: strictly after "
        "the exposure start, at or before the window's end. Outcomes are read "
        "from the person's derived justice events. new_case, new_charge, and "
        "reconviction count only in another case of the same person (an event "
        "whose related case is unknown does not count); failure_to_appear, "
        "release_violation, revocation, and rearrest count in any case. The "
        f"windows are {', '.join(str(w) for w in WINDOWS_DAYS)} days.",
    ),
    (
        "Right-censoring and followed cohorts",
        "Follow-up ends at the source's coverage end: nothing after the day "
        "following coverage_end at 00:00 UTC is in the data, so an absent "
        "outcome after that instant means nothing. A cohort member is followed "
        "for window w when exposure start + w days is strictly before that "
        "instant. A fixed-window rate's denominator is the followed members "
        "and its numerator the followed members with an outcome in the "
        "window; the eligible count is the whole cohort and is published "
        "beside the rate.",
    ),
    (
        "Kaplan-Meier",
        "Over the whole cohort, each member contributes its time to first "
        "outcome (an event) or to the coverage end (a censoring), measured "
        "from the exposure start. The product-limit survival S(t) is the "
        "product over the distinct event times t_i <= t of (1 - d_i / n_i), "
        "with d_i the events at t_i and n_i the members at risk at t_i; events "
        "are counted before censorings at the same time. S is evaluated at "
        "t = w days and published as the cumulative incidence 1 - S(w) with "
        "the Greenwood standard error S(t) * sqrt(sum of d_i / (n_i * (n_i - "
        "d_i))) and a symmetric 95% interval clipped to [0, 1]. When every "
        "member at risk fails at some time, S is 0 from then on and the "
        "standard error is 0. When every member is followed for w, 1 - S(w) "
        "equals the fixed-window rate.",
    ),
    (
        "Observable outcomes",
        "Every source declares which outcome types it can document, and for a "
        "revocation which scope: a revoked pretrial release after a pretrial "
        "release, a revoked supervision a sentence imposed after a disposition "
        "or a sentence (Revocation scopes). A metric whose outcome - or "
        "revocation scope - the source cannot observe is not observable for "
        "that source: no observation is published for it, never a zero. "
        "Source limitations lists what each source documents.",
    ),
)

ATTRIBUTION_TEXT: tuple[str, ...] = (
    "Every judge-level metric uses only events whose attribution satisfies "
    "the metric's documented inclusion rules. Each metric below states its "
    "rule: the decision type, the actor types, and the discretion "
    "classification a row must carry, and the assignment gate that ties the "
    "row to the judge. A court's metrics are computed over the cases filed "
    "in the court, whatever gate the rule names.",
    "A statutory release (actor legislature_or_mandatory_rule, discretion "
    "mandatory) and a decision whose actor or discretion is unknown are never "
    "attributed to a judge, whatever a rule admits; the court-level counts "
    "statutory_release_count and unknown_actor_pretrial_count report them. A "
    "prosecutor's dismissal is not a judicial dismissal: the judicial "
    "dismissal rate counts only charges dismissed with the judge as the "
    "disposing actor.",
    "A source records only some gates: one may name the judge of a "
    "disposition and of a sentencing but no judge assignment and no "
    "deciding judge. A judge metric whose gate the source does not record "
    "is not attributable for that source: no observation is published for "
    "the judge, never a zero; the court-level metrics, computed over the "
    "court's cases, still count the rows. Source limitations lists the gates "
    "each source records.",
)

# (version, what changed) — oldest first; served by ``GET /metrics`` as ``changelog``.
CHANGELOG: tuple[tuple[str, str], ...] = (
    (
        "0.1",
        "first registry (Phase 3 Step 1): descriptive counts and shares, "
        "fixed-window rates and Kaplan-Meier cumulative incidence after "
        "pretrial release, disposition, and sentence, the disposition "
        "distribution, the judicial dismissal rate, and the medians; "
        "right-censoring at the source's coverage end; incarceration deferral; "
        "Wilson and Greenwood intervals; suppression below a denominator of 10.",
    ),
    (
        "0.2",
        "Exposure is deferred by every incarceration term of the person, not the "
        "index case's alone (Phase 3 finding 1.4).",
    ),
    (
        "0.3",
        "Observed-to-expected ratios with partial pooling and bootstrap intervals "
        "are defined and computed for three judge metrics; they are not served "
        "until the validation that methodology 1.0 publishes.",
    ),
    (
        "1.0",
        "The expected-outcome model, observed-to-expected ratios with partial "
        "pooling and bootstrap intervals, and their validation (docs/VALIDATION.md) "
        "are published; the known limitations are unchanged.",
    ),
    (
        "1.1",
        "Real-data semantics (registry version 3, specification version 3): the "
        "disposition family is attributed to the disposing judge the source "
        "records; a judge metric whose gate a source does not record is not "
        "attributable and publishes nothing; only a final disposition disposes "
        "of a charge; each sentencing decision counts once; a revocation is "
        "observable per scope; every descriptive metric adds one observation per "
        "calendar year, and a row outside the coverage window enters none; every "
        "threshold carries its rationale and measured cohorts; coverage "
        "statistics, source limitations, and per-source model availability are "
        "published; the known limitations are unchanged.",
    ),
)

# The brief's <risk_adjustment><interpretation>, verbatim.
INTERPRETATION = (
    "An O/E ratio above 1 means observed outcomes exceeded the model's expected "
    "count for the defined cohort. A ratio below 1 means observed outcomes were "
    "below the model's expected count. It must not be described as proof that the "
    "judge caused the difference."
)

# The adjusted statistics (methodology 1.0): rendered into docs/METHODOLOGY.md and
# served by GET /metrics as `adjustment`, both through `adjustment_prose`.
ADJUSTMENT_INTRO = (
    "The adjusted metrics compare what a judge's cohort shows with what a versioned "
    "model expects for defendants with similar observable case characteristics under "
    "the source's average practice. Every element below is rendered from the outcome "
    "model specification (data/reference/outcome_model.yaml) and the metric registry; "
    "the model's validation is docs/VALIDATION.md."
)
KNOWN_AT_TEXT: dict[str, str] = {
    FILED_AT: (
        "the index case's filing (00:00 UTC of its filing date), which precedes every "
        "index event of the case: only rows strictly before it are read"
    ),
    DECISION_AT: (
        "the pretrial decision: only the index case's charges filed strictly before it are read"
    ),
    INDEX_AT: "the index event itself (its calendar year)",
}
EXPECTED_COUNT_TEXT = (
    "For every eligible index event i the model gives a predicted probability p_i of "
    "the outcome from the published coefficients. A judge's expected count E is the sum "
    "of p_i over the judge's members in the ratio (the brief's Expected_j = SUM(p_i)); "
    "the observed count O is the number of those members with the outcome; n is their "
    "number. O / n is the observed rate, E / n the expected rate, and O / E the "
    "unpooled ratio. A member whose features are missing under an exclude rule is "
    "outside the ratio and counted in the eligible count."
)
POOLING_TEXT = (
    "A judge's O / E is noisy when E is small, so it is shrunk toward 1 by an "
    "empirical-Bayes gamma-Poisson model: O | theta ~ Poisson(theta E), theta ~ "
    "Gamma(alpha, alpha), mean 1 and variance 1 / alpha. The shape alpha is fitted by "
    "maximum marginal (negative-binomial) likelihood over every judge of the source "
    "with E > 0, suppressed or not, on {grid} points log-spaced over [{low:g}, "
    "{high:g}] refined by golden-section search; a maximum at the upper bound means no "
    "between-judge variation is detectable and every ratio is pulled almost all the "
    "way to 1. The published ratio is the posterior mean (alpha + O) / (alpha + E); "
    "the pooling weight E / (E + alpha) is the share of it that is the judge's own "
    "O / E, the rest being the prior mean, 1."
)
INTERVAL_TEXT = (
    "A person-cluster bootstrap with the model refitted: {replicates} replicates, each "
    "drawing the source's persons with replacement from the model's seeded stream "
    "(seed {seed}) and refitting the model on the redrawn index events; per replicate "
    "every member is re-predicted from that replicate's coefficients, each judge's "
    "weighted O and E are recomputed, alpha is refitted, and the pooled ratio is "
    "recomputed. The interval is the {lower:g}th and {upper:g}th percentiles (linear "
    "interpolation) over the converged replicates; a replicate whose refit did not "
    "converge is skipped. The replicate coefficients are stored with the model, so a "
    "recompute reproduces the interval exactly. The interval describes the sampling "
    "variability of the pooled estimate, which is shrunk toward 1: it is not a "
    "confidence interval for the judge's true ratio, and it covers the true ratio of a "
    "judge far from 1 less often than its nominal level (docs/VALIDATION.md)."
)
CONTROLS_TEXT: tuple[tuple[str, str], ...] = (
    (
        "Temporal",
        "The calendar year of the index event is a feature, so each member's "
        "expected outcome is the source's practice in the same year: a judge is "
        "compared with contemporaneous cohorts. A year the model has not seen is "
        "scored at the latest year it has; the temporal split in docs/VALIDATION.md "
        "measures what that costs when outcomes trend across years.",
    ),
    (
        "Jurisdiction",
        "The court of filing and its jurisdiction are features, so a member's "
        "expected outcome is the practice of the court the case was filed in. Judges "
        "are compared only within their source's model, never across sources, whose "
        "legal regimes, procedures, and recording differ.",
    ),
)
LIMITATIONS_TEXT: tuple[str, ...] = (
    "Unobserved confounding and selection on unobservables: the model adjusts only for "
    "the recorded characteristics it lists. A judge whose docket differs in risk the "
    "records do not show carries that difference in the ratio, whatever the judge's "
    "decisions (the synthetic generator's latent propensity is such a risk, by "
    "construction).",
    "Model misspecification: the model is a main-effects logistic regression. An "
    "interaction, a nonlinearity, or a trend it does not represent moves into the "
    "ratio; the temporal split shows that the models do not transport equally well "
    "(docs/VALIDATION.md).",
    "Restricted attributes excluded by policy: the model never reads a restricted "
    "attribute or a protected characteristic, so a planted or real difference by such "
    "an attribute remains in the residual. The subgroup calibration shows it: on the "
    "synthetic source the age band's planted effect appears in the subgroup ratios in "
    "the planted direction, so a judge whose docket skews young or old carries that "
    "difference in the ratio, while the negative control is calibrated "
    "(docs/VALIDATION.md).",
    "Intervals conditional on the specification: the bootstrap refits the same "
    "features, penalty, and functional form, so the uncertainty of those choices is "
    "not in the interval.",
)
VALIDATION_TEXT = (
    "docs/VALIDATION.md reports, per target and window, the temporal-split "
    "calibration, Brier score, ROC AUC, calibration in the large and slope, feature "
    "stability, missing-data sensitivity, the bootstrap stability of the judge-level "
    "estimates, subgroup calibration in aggregate, and, for a synthetic source, the "
    "recovery of the planted effects. It is generated by `judgemetrics validation "
    "report` and checked in CI."
)


@dataclass(frozen=True, slots=True)
class FeatureText:
    """One model feature as the methodology states it."""

    name: str
    description: str
    levels: str
    known_at: str
    missing: str
    leakage: str


@dataclass(frozen=True, slots=True)
class AdjustmentProse:
    """The "Adjusted statistics" prose, from the specification and the registry."""

    specification_version: int
    model_version: str
    intro: str
    interpretation: str
    model: str
    targets: tuple[tuple[str, str], ...]
    features: tuple[FeatureText, ...]
    exclusions: tuple[tuple[str, str], ...]
    expected_count: str
    pooling: str
    interval: str
    thresholds: tuple[tuple[str, str], ...]
    controls: tuple[tuple[str, str], ...]
    limitations: tuple[str, ...]
    validation: str


def _feature_levels(feature: FeatureSpec) -> str:
    if feature.data_levels:
        unseen = (
            "the latest seen level" if feature.unseen == UNSEEN_LATEST else "the reference level"
        )
        return (
            "the source's own levels, ordered by their number of index events (the "
            f"busiest is the reference); a level unseen in a fit is scored at {unseen}"
        )
    return ", ".join(
        f"{level} (reference)" if level == feature.reference else level
        for level in feature.fixed_levels
        if level != feature.missing_level
    )


def _scientific(value: float) -> str:
    """``1e-08`` as ``1e-8``."""
    mantissa, _, exponent = f"{value:.0e}".partition("e")
    return f"{mantissa}e{int(exponent)}"


def _feature_missing(feature: FeatureSpec) -> str:
    if feature.missing == EXCLUDE:
        return "an index event without a value is excluded from the model"
    return f"an index event without a value takes the level {feature.missing_level}"


def adjustment_prose(
    spec: OutcomeModelSpec | None = None, registry: Registry | None = None
) -> AdjustmentProse:
    """The adjusted-statistics prose ``docs/METHODOLOGY.md`` and ``GET /metrics`` share."""
    spec = spec or load_spec()
    registry = registry or load_registry()
    model = spec.model
    cohort = min(
        (metric.suppression_threshold for metric in registry.of_kind("observed_expected")),
        default=spec.thresholds.minimum_cohort,
    )
    tail = (1.0 - spec.bootstrap.level) / 2.0 * 100.0
    return AdjustmentProse(
        specification_version=spec.version,
        model_version=spec.model_version,
        intro=ADJUSTMENT_INTRO,
        interpretation=INTERPRETATION,
        model=(
            f"A regularized logistic regression ({model.penalty.upper()} penalty, lambda "
            f"{model.lam}, the intercept unpenalized), fitted by Newton-Raphson (at most "
            f"{model.max_iterations} iterations, gradient tolerance "
            f"{_scientific(model.tolerance)}): one model per source, target, and window "
            "over every eligible index event of the source, so every judge of the source "
            "is scored by the same model. The judge is never a term of the model. "
            f"Specification version {spec.version}, model version {spec.model_version}."
        ),
        targets=tuple(
            (
                target.name,
                target.description
                + (
                    ""
                    if target.windows_days is None
                    else " Windows: "
                    + ", ".join(str(window) for window in target.windows_days)
                    + " days."
                ),
            )
            for target in spec.targets
        ),
        features=tuple(
            FeatureText(
                name=feature.name,
                description=feature.description
                + (
                    ""
                    if feature.lookback_days is None
                    else f" The lookback is {feature.lookback_days} days."
                ),
                levels=_feature_levels(feature),
                known_at=KNOWN_AT_TEXT[feature.known_at],
                missing=_feature_missing(feature),
                leakage=feature.leakage,
            )
            for feature in spec.features
        ),
        exclusions=tuple((entry.name, entry.reason) for entry in spec.excluded),
        expected_count=EXPECTED_COUNT_TEXT,
        pooling=POOLING_TEXT.format(
            grid=spec.pooling.shape_grid,
            low=spec.pooling.shape_bounds[0],
            high=spec.pooling.shape_bounds[1],
        ),
        interval=INTERVAL_TEXT.format(
            replicates=spec.bootstrap.replicates,
            seed=spec.seed,
            lower=tail,
            upper=100.0 - tail,
        ),
        thresholds=(
            (
                "Events per column",
                "A model is fitted only when the fewer of its outcomes and non-outcomes "
                f"number at least {spec.thresholds.minimum_events_per_column} per design "
                "column (the intercept included); otherwise its ratios are withheld as "
                "model_unavailable, because a logistic fit with fewer events per column "
                "is unstable and overfits.",
            ),
            (
                "Cohort",
                f"A ratio is withheld below {cohort} members in the ratio "
                "(below_threshold): a ratio of two small counts is unstable well above "
                "the ten members a share needs, since its numerator and its denominator "
                "both move by chance.",
            ),
            (
                "Expected count",
                "A ratio is withheld below an expected count of "
                f"{spec.thresholds.minimum_expected:g} (expected_below_minimum): below it "
                "the ratio is a function of a handful of predicted events.",
            ),
        ),
        controls=CONTROLS_TEXT,
        limitations=LIMITATIONS_TEXT,
        validation=VALIDATION_TEXT,
    )


def _fill(text: str, *, initial: str = "", subsequent: str = "") -> str:
    return textwrap.fill(
        text,
        width=WIDTH,
        initial_indent=initial,
        subsequent_indent=subsequent,
        break_long_words=False,
        break_on_hyphens=False,
    )


def _bullet(text: str) -> str:
    return _fill(text, initial="- ", subsequent="  ")


def _numbered(index: int, text: str) -> str:
    prefix = f"{index}. "
    return _fill(text, initial=prefix, subsequent=" " * len(prefix))


def _attribution_lines(metric: MetricDefinitionSpec) -> Iterable[str]:
    rule = metric.attribution
    parts: list[str] = []
    if rule.decision_type is not None:
        parts.append(f"decision type {rule.decision_type}")
    if rule.actor_types is not None:
        parts.append(f"actor {' or '.join(rule.actor_types)}")
    if rule.discretion is not None:
        parts.append(f"discretion {' or '.join(rule.discretion)}")
    parts.append(f"gate: {GATE_TEXT[rule.assignment_gate]}")
    yield _bullet(f"Attribution: {'; '.join(parts)}.")
    if metric.counted:
        conditions = ", ".join(
            f"{column} = {str(value).lower() if isinstance(value, bool) else value}"
            for column, value in metric.counted
        )
        yield _bullet(f"Counted rows: {conditions}.")


def _metric_section(metric: MetricDefinitionSpec) -> list[str]:
    lines = [f"### {metric.name}", ""]
    lines.append(_bullet(f"Slug: `{metric.slug}` (version {metric.version})."))
    lines.append(
        _bullet(
            f"Kind: {KIND_TEXT[metric.kind]}; unit: {metric.unit}; subjects: "
            f"{', '.join(metric.subject_types)}."
        )
    )
    lines.append(_bullet(f"What it says: {metric.description}"))
    lines.append(_bullet(f"Numerator: {metric.numerator}"))
    lines.append(_bullet(f"Denominator: {metric.denominator}"))
    lines.append(_bullet(f"Eligibility: {metric.eligibility}"))
    lines.extend(_attribution_lines(metric))
    if metric.is_windowed:
        scope = "" if metric.revocation_scope is None else f" (scope {metric.revocation_scope})"
        lines.append(
            _bullet(
                f"Index event: {metric.index_event}; outcome: {metric.outcome}{scope}; "
                f"windows: {', '.join(str(w) for w in metric.windows_days or ())} days."
            )
        )
    if metric.dimension is not None:
        lines.append(_bullet(f"Dimension: one observation per {metric.dimension} value."))
    if metric.measure is not None:
        lines.append(_bullet(f"Measure: {metric.measure}."))
    if metric.adjustment is not None:
        lines.append(
            _bullet(
                f"Adjustment: outcome model target `{metric.adjustment.target}` "
                "(data/reference/outcome_model.yaml); the pooled ratio, its "
                "pooling weight, and its bootstrap interval are defined under "
                "Adjusted statistics."
            )
        )
        lines.append(
            _bullet(
                f"Suppression threshold: {metric.suppression_threshold} (suppressed "
                "below this cohort), and suppressed below an expected count of "
                f"{metric.adjustment.minimum_expected:g} or without a fitted model."
            )
        )
        lines.append("")
        return lines
    lines.append(
        _bullet(
            f"Suppression threshold: {metric.suppression_threshold}"
            + (
                " (never suppressed: a count)."
                if metric.suppression_threshold == 0
                else " (suppressed below this denominator)."
            )
        )
    )
    lines.append("")
    return lines


def _adjustment_lines(prose: AdjustmentProse) -> list[str]:
    lines = ["## Adjusted statistics", "", _fill(prose.intro), ""]
    lines.extend([_fill(f"**Interpretation.** {prose.interpretation}"), ""])
    lines.extend(["### The model", "", _fill(prose.model), ""])
    lines.extend(["### Targets", ""])
    lines.extend(_bullet(f"`{name}`: {text}") for name, text in prose.targets)
    lines.extend(["", "### Features", ""])
    for feature in prose.features:
        lines.append(
            _bullet(
                f"`{feature.name}`: {feature.description} Levels: {feature.levels}. "
                f"Known at: {feature.known_at}. Missing: {feature.missing}. Leakage: "
                f"{feature.leakage}"
            )
        )
    lines.extend(["", "### Exclusions", ""])
    lines.extend(_bullet(f"`{name}`: {reason}") for name, reason in prose.exclusions)
    lines.extend(["", "### Expected counts", "", _fill(prose.expected_count), ""])
    lines.extend(["### Partial pooling", "", _fill(prose.pooling), ""])
    lines.extend(["### Interval", "", _fill(prose.interval), ""])
    lines.extend(["### Thresholds", ""])
    lines.extend(_bullet(f"**{term}**: {text}") for term, text in prose.thresholds)
    lines.extend(["", "### Temporal and jurisdiction controls", ""])
    lines.extend(_bullet(f"**{term}**: {text}") for term, text in prose.controls)
    lines.extend(["", "### Limitations of adjustment", ""])
    lines.extend(_numbered(index, text) for index, text in enumerate(prose.limitations, 1))
    lines.extend(["", "### Validation", "", _fill(prose.validation), ""])
    return lines


def _periods_lines(registry: Registry) -> list[str]:
    periods = registry.periods
    kinds = ", ".join(kind for kind in KIND_TEXT if kind in periods.calendar_year_kinds)
    lines = ["## Periods", "", _fill(f"**Whole window.** {periods.whole_window}"), ""]
    lines.append(_fill(f"**Calendar years.** {periods.calendar_year}"))
    lines.append("")
    lines.append(_fill(f"Kinds with calendar years: {kinds}. Anchors:"))
    lines.append("")
    lines.extend(
        _bullet(f"`{population}`: {anchor}") for population, anchor in periods.anchors.items()
    )
    lines.append("")
    return lines


def _revocation_lines(registry: Registry) -> list[str]:
    scopes = registry.revocation_scopes
    lines = ["## Revocation scopes", ""]
    lines.append(
        _fill(
            "A revocation outcome means a different event after each index event. "
            "Each revocation metric reads the scope of its index event, and a source "
            "observes it only when it documents that scope:"
        )
    )
    lines.append("")
    lines.extend(_bullet(f"`{name}`: {text}") for name, text in scopes.definitions.items())
    lines.append("")
    lines.extend(
        _bullet(f"After a `{index_event}` index event, a revocation is of scope `{scope}`.")
        for index_event, scope in scopes.by_index_event.items()
    )
    lines.append("")
    return lines


def _source_lines(registry: Registry) -> list[str]:
    """Every registered source: its gates, person key, observable outcomes, notes."""
    from judgemetrics.ingest.registry import load_builtin_connectors, registered_connectors
    from judgemetrics.metrics.registry import JUDGE_GATES
    from judgemetrics.metrics.windows import ANY_CASE_OUTCOMES, OTHER_CASE_OUTCOMES

    load_builtin_connectors()
    outcomes = sorted(OTHER_CASE_OUTCOMES | ANY_CASE_OUTCOMES)
    lines = ["## Source limitations", ""]
    lines.append(
        _fill(
            "What each registered source can and cannot show, from the declaration of "
            "its connector: the judge gates it records (a judge metric gated otherwise "
            "is not attributable), its person-key scope, the outcomes and revocation "
            "scopes it documents (a metric over any other is not observable), and its "
            "own notes."
        )
    )
    lines.append("")
    for source_id, info in registered_connectors():
        capabilities = info.capabilities
        recorded = ", ".join(capabilities.judge_gates) or "none"
        missing = ", ".join(g for g in JUDGE_GATES if g not in capabilities.judge_gates)
        scope = capabilities.person_key_scope or "none (the source records no person)"
        observed = ", ".join(o for o in outcomes if o in info.observable_outcomes) or "none"
        unobserved = ", ".join(o for o in outcomes if o not in info.observable_outcomes)
        revocations = ", ".join(capabilities.revocation_scopes) or "none"
        lines.extend([f"### `{source_id}`", ""])
        lines.append(_bullet(f"Owner: {info.owner}."))
        lines.append(
            _bullet(f"Judge gates recorded: {recorded}; not recorded: {missing or 'none'}.")
        )
        lines.append(_bullet(f"Person key: {scope}."))
        lines.append(
            _bullet(
                f"Outcomes documented: {observed}; not documented: {unobserved or 'none'}; "
                f"revocation scopes: {revocations}."
            )
        )
        lines.extend(_bullet(note) for note in info.limitations)
        lines.append("")
    del registry
    return lines


def _coverage_lines() -> list[str]:
    from judgemetrics.metrics.coverage import DEFINITIONS

    lines = ["## Coverage statistics", ""]
    lines.append(
        _fill(
            "Every compute records, per source, per jurisdiction of its courts, and per "
            "court, the brief's six coverage statistics and the unknown-actor share - "
            "each a numerator over a denominator with its share, aggregates only. "
            "`judgemetrics metrics coverage` prints the latest; `metrics verify` "
            "recomputes them."
        )
    )
    lines.append("")
    lines.extend(_bullet(f"`{name}`: {text}") for name, text in DEFINITIONS.items())
    lines.append("")
    return lines


def _availability_lines(spec: OutcomeModelSpec) -> list[str]:
    availability = spec.availability
    lines = ["### Availability", ""]
    lines.append(
        _fill(
            "A target is fitted for a source only when the source meets three "
            "conditions; otherwise the catalogue records it unavailable with the reason "
            "of the first condition it fails, and the adjusted metrics over it publish "
            "nothing for that source:"
        )
    )
    lines.append("")
    lines.append(_numbered(1, f"It records the population's judge. {availability.gate}"))
    lines.append(_numbered(2, f"It documents the outcome. {availability.outcome}"))
    lines.append(
        _numbered(
            3,
            "Its person key crosses cases (person-history features: "
            f"{', '.join(spec.person_history_features)}). {availability.person_key}",
        )
    )
    lines.append("")
    return lines


def _suppression_lines(registry: Registry) -> list[str]:
    suppression = registry.suppression
    lines = ["## Suppression", ""]
    lines.append(_fill(f"Default threshold: {suppression.default_threshold}."))
    lines.append("")
    lines.append(_fill(suppression.rule))
    lines.append("")
    lines.append(_fill(suppression.rationale))
    lines.append("")
    lines.extend(["### Thresholds and their reasons", ""])
    for group in suppression.thresholds:
        slugs = ", ".join(f"`{slug}`" for slug in group.metrics)
        lines.append(_bullet(f"**{group.threshold}** - {slugs}: {group.rationale}"))
    lines.append("")
    lines.extend(["### The eligible count of a suppressed observation", ""])
    lines.append(_fill(suppression.eligible_count))
    lines.append("")
    lines.extend(["### Measured cohorts", ""])
    lines.append(_fill(f"Measured on {suppression.measured_on}. {suppression.measurement_method}"))
    lines.append("")
    for item in suppression.measurements:
        window = "" if item.window_days is None else f", {item.window_days}-day window"
        quantiles = ", ".join(f"{name} {value:,}" for name, value in item.quantiles)
        lines.append(
            _bullet(
                f"`{item.name}` ({item.source}, {item.subject_type}, "
                f"{item.period.replace('_', ' ')}{window}): {item.cohorts:,} cohorts; "
                f"{quantiles}; {item.under_threshold:.3f} under the threshold."
            )
        )
    lines.append("")
    named: dict[str, tuple[str, ...]] = {}
    for item in suppression.measurements:
        named.setdefault(item.name, item.metrics)
    lines.extend(
        _bullet(f"`{name}`: {', '.join(f'`{slug}`' for slug in slugs)}.")
        for name, slugs in named.items()
    )
    lines.append("")
    return lines


def render_methodology(registry: Registry | None = None) -> str:
    """The Markdown document (LF line endings, one trailing newline, 80 columns)."""
    registry = registry or load_registry()
    lines: list[str] = [PATH_COMMENT, GENERATED_NOTICE, "# Methodology", ""]
    lines.append(
        _fill(
            f"Registry version {registry.version}; methodology version "
            f"{registry.methodology_version}; {len(registry.metrics)} metrics."
        )
    )
    lines.append("")
    lines.append(
        _fill(
            "This document is rendered from the versioned metric registry "
            "(`data/reference/metric_registry.yaml`), the contract every published "
            "number is computed against. These statistics describe associations in "
            "available records. They do not prove that a judicial decision caused a "
            "later event. There is no composite, ideological, partisan, or "
            "best-or-worst judge score."
        )
    )
    lines.append("")
    lines.extend(["## How to read a number", ""])
    for term, text in HOW_TO_READ:
        lines.append(_bullet(f"**{term}**: {text}"))
    lines.append("")
    lines.extend(["## Index events, exposure, and censoring", ""])
    for term, text in SEMANTICS:
        lines.append(_fill(f"**{term}.** {text}"))
        lines.append("")
    lines.extend(_periods_lines(registry))
    lines.extend(_revocation_lines(registry))
    lines.extend(["## Attribution", ""])
    for paragraph in ATTRIBUTION_TEXT:
        lines.append(_fill(paragraph))
        lines.append("")
    lines.extend(_source_lines(registry))
    lines.extend(_coverage_lines())
    if registry.of_kind("observed_expected"):
        spec = load_spec()
        adjustment = _adjustment_lines(adjustment_prose(spec=spec, registry=registry))
        # The availability rules sit after the model description (methodology 1.1).
        at = adjustment.index("### Targets")
        lines.extend([*adjustment[:at], *_availability_lines(spec), *adjustment[at:]])
    lines.extend(["## Metrics", ""])
    lines.append(
        _fill(
            "One section per metric, in registry order. A metric's formula is its "
            "numerator over its denominator; its eligibility states which rows "
            "enter; its attribution rule states how a row is tied to the subject."
        )
    )
    lines.append("")
    for metric in registry.metrics.values():
        lines.extend(_metric_section(metric))
    lines.extend(_suppression_lines(registry))
    lines.extend(["## Known limitations", ""])
    lines.append(
        _fill(
            "The brief's statistical warnings, published verbatim and never softened "
            "for presentation:"
        )
    )
    lines.append("")
    for index, warning in enumerate(registry.known_limitations, start=1):
        lines.append(_numbered(index, warning))
    lines.append("")
    lines.extend(["## Methodology changelog", ""])
    for version, text in CHANGELOG:
        lines.append(_bullet(f"{version} - {text}"))
    lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n"


def resolve_output(path: Path) -> Path:
    """An absolute path as given; a relative one under the repository root."""
    return (path if path.is_absolute() else REPO_ROOT / path).resolve()


def check_methodology(path: Path, registry: Registry | None = None) -> list[str]:
    """The unified diff between the file at ``path`` and the render; empty when equal."""
    rendered = render_methodology(registry)
    try:
        current = path.read_bytes().decode("utf-8")
    except FileNotFoundError:
        return [f"--- {path} is missing", f"+++ render ({len(rendered.splitlines())} lines)"]
    if current == rendered:
        return []
    return list(
        difflib.unified_diff(
            current.splitlines(),
            rendered.splitlines(),
            fromfile=str(path),
            tofile="render",
            lineterm="",
        )
    )


def write_methodology(path: Path, registry: Registry | None = None) -> None:
    """Write the render to ``path`` (LF, UTF-8), creating parent directories."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(render_methodology(registry).encode("utf-8"))
