# src/judgemetrics/metrics/methodology.py
"""Render ``docs/METHODOLOGY.md`` from the metric registry.

The committed document is a snapshot of ``render_methodology()`` the way
``docs/openapi.json`` is a snapshot of the OpenAPI document:
``judgemetrics methodology render`` writes it, ``--check`` (and the unit
test) fails when the file differs, so a registry change reaches the
methodology page in the same pull request. The text is wrapped at 80
columns; the brief's statistical warnings are rendered verbatim,
unsoftened, as the "Known limitations" list. A relative output path is
resolved under the repository root, never the working directory.
"""

from __future__ import annotations

import difflib
import textwrap
from collections.abc import Iterable
from pathlib import Path

from judgemetrics.config import REPO_ROOT
from judgemetrics.metrics.registry import (
    WINDOWS_DAYS,
    MetricDefinitionSpec,
    Registry,
    load_registry,
)

DEFAULT_OUTPUT = Path("docs") / "METHODOLOGY.md"
WIDTH = 80
PATH_COMMENT = "<!-- docs/METHODOLOGY.md -->"
GENERATED_NOTICE = (
    "<!-- Generated by `judgemetrics methodology render` from\n"
    "     data/reference/metric_registry.yaml. Do not edit by hand: change the\n"
    "     registry and re-render. -->"
)

GATE_TEXT: dict[str, str] = {
    "deciding_judge": "the deciding judge (the decision's judge is the subject)",
    "assigned_at_time": (
        "the judge assigned at the event time (the time falls in one of the "
        "judge's assignment intervals on the case, start <= t < end, an open end "
        "unbounded)"
    ),
    "assigned_ever": "any judge with at least one assignment on the case",
    "sentencing_judge": "the sentencing judge (the sentence's judge is the subject)",
    "court_of_case": "the court of the case (a court-only metric)",
}
KIND_TEXT: dict[str, str] = {
    "count": "count",
    "share": "share (numerator over denominator, Wilson interval)",
    "windowed_rate": "fixed-window rate per observation window (Wilson interval)",
    "survival": "Kaplan-Meier cumulative incidence per observation window",
    "distribution": "distribution of counts by dimension value",
    "median": "median",
}

HOW_TO_READ: tuple[tuple[str, str], ...] = (
    (
        "Numerator",
        "the count of rows or members that met the metric's condition, stated beside every number.",
    ),
    (
        "Denominator",
        "the count the numerator is divided by: the attributed rows for a "
        "share, the followed cohort members for a fixed-window rate, the "
        "whole cohort for a survival estimate, the values a median is taken "
        "over. A count has no denominator.",
    ),
    (
        "Date range",
        "the period the observation covers: the source's coverage window "
        "(period_start to period_end), the dates within which every counted "
        "row falls.",
    ),
    (
        "Coverage",
        "the source the rows come from, its coverage window, and the snapshot "
        "(a content hash of the exported tables) the number was computed "
        "from, so it can be reproduced later.",
    ),
    (
        "Sample size",
        "the eligible count (the whole cohort before any follow-up "
        "restriction) and the cohort size (the denominator). The eligible "
        "count is published even when the number itself is suppressed; the "
        "denominator is withheld with the number.",
    ),
    (
        "Interval",
        "a 95% Wilson score interval for every share and fixed-window rate, "
        "a Greenwood interval for every Kaplan-Meier estimate. Adjusted "
        "statistics (Phase 4) carry their own intervals and methodology "
        "version; none is published under this version.",
    ),
    (
        "Suppression",
        "a number whose denominator is below the metric's suppression "
        "threshold is withheld and marked suppressed — the numerator, "
        "denominator, value, distribution, and interval leave the API as "
        "null and the threshold is stated per metric below and beside every "
        "observation.",
    ),
    (
        "Versions",
        "every observation records the registry version, the methodology "
        "version, the code version, and the snapshot it was computed under.",
    ),
)

SEMANTICS: tuple[tuple[str, str], ...] = (
    (
        "Index events",
        "An index event is one person, one case, one kind, and one instant "
        "(index_at): the moment follow-up is measured from. Three kinds exist. "
        "pretrial_release: an attributed pretrial decision (the metric's "
        "attribution rule applies) with detained = false and a release time; "
        "the index time is the release time. disposition: a disposed case - "
        "one whose charges carry a disposition other than pending or missing "
        "and a disposition time - at the case disposition time, the latest "
        "disposed_at among its disposed charges, attributed to the judge "
        "assigned at that time; one index event per person with a disposed "
        "charge in the case. sentence: an attributed sentence at sentence_at, "
        "attributed to the sentencing judge. A court's index events are those "
        "of the court's cases.",
    ),
    (
        "Exposure",
        "Time at risk starts at the index time. For the disposition and "
        "sentence kinds, when the sentence carries a positive "
        "incarceration_days, exposure starts at sentence_at + "
        "incarceration_days instead: the incarceration term defers time at "
        "risk. For the sentence kind the deferring sentence is the index "
        "sentence itself; for the disposition kind it is the sentence of the "
        "same case and person, the latest term end when there are several. "
        "The pretrial_release kind is never deferred. Documented limitation: "
        "only the sentence of the index case defers exposure; other terms the "
        "same person serves - an earlier sentence still running, a term in "
        "another case or jurisdiction - are not modelled, so time at risk is "
        "overstated for such persons and their rates are biased downward.",
    ),
    (
        "Outcomes and windows",
        "An outcome counts for a window w when an event of the outcome type "
        "occurs in (exposure start, exposure start + w days]: strictly after "
        "the exposure start, at or before the window's end. Outcomes are read "
        "from the person's derived justice events. new_case, new_charge, and "
        "reconviction count only in another case of the same person (an event "
        "whose related case is unknown does not count); failure_to_appear, "
        "release_violation, revocation, and rearrest count in any case. The "
        f"windows are {', '.join(str(w) for w in WINDOWS_DAYS)} days.",
    ),
    (
        "Right-censoring and followed cohorts",
        "Follow-up ends at the source's coverage end: nothing after the day "
        "following coverage_end at 00:00 UTC is in the data, so an absent "
        "outcome after that instant means nothing. A cohort member is followed "
        "for window w when exposure start + w days is strictly before that "
        "instant. A fixed-window rate's denominator is the followed members "
        "and its numerator the followed members with an outcome in the "
        "window; the eligible count is the whole cohort and is published "
        "beside the rate.",
    ),
    (
        "Kaplan-Meier",
        "Over the whole cohort, each member contributes its time to first "
        "outcome (an event) or to the coverage end (a censoring), measured "
        "from the exposure start. The product-limit survival S(t) is the "
        "product over the distinct event times t_i <= t of (1 - d_i / n_i), "
        "with d_i the events at t_i and n_i the members at risk at t_i; events "
        "are counted before censorings at the same time. S is evaluated at "
        "t = w days and published as the cumulative incidence 1 - S(w) with "
        "the Greenwood standard error S(t) * sqrt(sum of d_i / (n_i * (n_i - "
        "d_i))) and a symmetric 95% interval clipped to [0, 1]. When every "
        "member at risk fails at some time, S is 0 from then on and the "
        "standard error is 0. When every member is followed for w, 1 - S(w) "
        "equals the fixed-window rate.",
    ),
    (
        "Observable outcomes",
        "Every source declares which outcome types it can document. A metric "
        "whose outcome the source cannot observe is not observable for that "
        "source: no observation is published for it, never a zero. The "
        "synthetic source documents new_case, new_charge, reconviction, "
        "failure_to_appear, and revocation; release_violation and rearrest "
        "need a source that records them.",
    ),
)

ATTRIBUTION_TEXT: tuple[str, ...] = (
    "Every judge-level metric uses only events whose attribution satisfies "
    "the metric's documented inclusion rules. Each metric below states its "
    "rule: the decision type, the actor types, and the discretion "
    "classification a row must carry, and the assignment gate that ties the "
    "row to the judge. A court's metrics are computed over the cases filed "
    "in the court, whatever gate the rule names.",
    "A statutory release (actor legislature_or_mandatory_rule, discretion "
    "mandatory) and a decision whose actor or discretion is unknown are never "
    "attributed to a judge, whatever a rule admits; the court-level counts "
    "statutory_release_count and unknown_actor_pretrial_count report them. A "
    "prosecutor's dismissal is not a judicial dismissal: the judicial "
    "dismissal rate counts only charges dismissed with the judge as the "
    "disposing actor.",
)

# (version, what changed) — oldest first; served by ``GET /metrics`` as ``changelog``.
CHANGELOG: tuple[tuple[str, str], ...] = (
    (
        "0.1",
        "first registry (Phase 3 Step 1): descriptive counts and shares, "
        "fixed-window rates and Kaplan-Meier cumulative incidence after "
        "pretrial release, disposition, and sentence, the disposition "
        "distribution, the judicial dismissal rate, and the medians; "
        "right-censoring at the source's coverage end; incarceration deferral; "
        "Wilson and Greenwood intervals; suppression below a denominator of 10.",
    ),
)


def _fill(text: str, *, initial: str = "", subsequent: str = "") -> str:
    return textwrap.fill(
        text,
        width=WIDTH,
        initial_indent=initial,
        subsequent_indent=subsequent,
        break_long_words=False,
        break_on_hyphens=False,
    )


def _bullet(text: str) -> str:
    return _fill(text, initial="- ", subsequent="  ")


def _numbered(index: int, text: str) -> str:
    prefix = f"{index}. "
    return _fill(text, initial=prefix, subsequent=" " * len(prefix))


def _attribution_lines(metric: MetricDefinitionSpec) -> Iterable[str]:
    rule = metric.attribution
    parts: list[str] = []
    if rule.decision_type is not None:
        parts.append(f"decision type {rule.decision_type}")
    if rule.actor_types is not None:
        parts.append(f"actor {' or '.join(rule.actor_types)}")
    if rule.discretion is not None:
        parts.append(f"discretion {' or '.join(rule.discretion)}")
    parts.append(f"gate: {GATE_TEXT[rule.assignment_gate]}")
    yield _bullet(f"Attribution: {'; '.join(parts)}.")
    if metric.counted:
        conditions = ", ".join(
            f"{column} = {str(value).lower() if isinstance(value, bool) else value}"
            for column, value in metric.counted
        )
        yield _bullet(f"Counted rows: {conditions}.")


def _metric_section(metric: MetricDefinitionSpec) -> list[str]:
    lines = [f"### {metric.name}", ""]
    lines.append(_bullet(f"Slug: `{metric.slug}` (version {metric.version})."))
    lines.append(
        _bullet(
            f"Kind: {KIND_TEXT[metric.kind]}; unit: {metric.unit}; subjects: "
            f"{', '.join(metric.subject_types)}."
        )
    )
    lines.append(_bullet(f"What it says: {metric.description}"))
    lines.append(_bullet(f"Numerator: {metric.numerator}"))
    lines.append(_bullet(f"Denominator: {metric.denominator}"))
    lines.append(_bullet(f"Eligibility: {metric.eligibility}"))
    lines.extend(_attribution_lines(metric))
    if metric.is_windowed:
        lines.append(
            _bullet(
                f"Index event: {metric.index_event}; outcome: {metric.outcome}; "
                f"windows: {', '.join(str(w) for w in metric.windows_days or ())} days."
            )
        )
    if metric.dimension is not None:
        lines.append(_bullet(f"Dimension: one observation per {metric.dimension} value."))
    if metric.measure is not None:
        lines.append(_bullet(f"Measure: {metric.measure}."))
    lines.append(
        _bullet(
            f"Suppression threshold: {metric.suppression_threshold}"
            + (
                " (never suppressed: a count)."
                if metric.suppression_threshold == 0
                else " (suppressed below this denominator)."
            )
        )
    )
    lines.append("")
    return lines


def render_methodology(registry: Registry | None = None) -> str:
    """The Markdown document (LF line endings, one trailing newline, 80 columns)."""
    registry = registry or load_registry()
    lines: list[str] = [PATH_COMMENT, GENERATED_NOTICE, "# Methodology", ""]
    lines.append(
        _fill(
            f"Registry version {registry.version}; methodology version "
            f"{registry.methodology_version}; {len(registry.metrics)} metrics."
        )
    )
    lines.append("")
    lines.append(
        _fill(
            "This document is rendered from the versioned metric registry "
            "(`data/reference/metric_registry.yaml`), the contract every published "
            "number is computed against. These statistics describe associations in "
            "available records. They do not prove that a judicial decision caused a "
            "later event. There is no composite, ideological, partisan, or "
            "best-or-worst judge score."
        )
    )
    lines.append("")
    lines.extend(["## How to read a number", ""])
    for term, text in HOW_TO_READ:
        lines.append(_bullet(f"**{term}**: {text}"))
    lines.append("")
    lines.extend(["## Index events, exposure, and censoring", ""])
    for term, text in SEMANTICS:
        lines.append(_fill(f"**{term}.** {text}"))
        lines.append("")
    lines.extend(["## Attribution", ""])
    for paragraph in ATTRIBUTION_TEXT:
        lines.append(_fill(paragraph))
        lines.append("")
    lines.extend(["## Metrics", ""])
    lines.append(
        _fill(
            "One section per metric, in registry order. A metric's formula is its "
            "numerator over its denominator; its eligibility states which rows "
            "enter; its attribution rule states how a row is tied to the subject."
        )
    )
    lines.append("")
    for metric in registry.metrics.values():
        lines.extend(_metric_section(metric))
    lines.extend(["## Suppression", ""])
    lines.append(_fill(f"Default threshold: {registry.suppression.default_threshold}."))
    lines.append("")
    lines.append(_fill(registry.suppression.rule))
    lines.append("")
    lines.append(_fill(registry.suppression.rationale))
    lines.append("")
    lines.extend(["## Known limitations", ""])
    lines.append(
        _fill(
            "The brief's statistical warnings, published verbatim and never softened "
            "for presentation:"
        )
    )
    lines.append("")
    for index, warning in enumerate(registry.known_limitations, start=1):
        lines.append(_numbered(index, warning))
    lines.append("")
    lines.extend(["## Methodology changelog", ""])
    for version, text in CHANGELOG:
        lines.append(_bullet(f"{version} - {text}"))
    lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n"


def resolve_output(path: Path) -> Path:
    """An absolute path as given; a relative one under the repository root."""
    return (path if path.is_absolute() else REPO_ROOT / path).resolve()


def check_methodology(path: Path, registry: Registry | None = None) -> list[str]:
    """The unified diff between the file at ``path`` and the render; empty when equal."""
    rendered = render_methodology(registry)
    try:
        current = path.read_bytes().decode("utf-8")
    except FileNotFoundError:
        return [f"--- {path} is missing", f"+++ render ({len(rendered.splitlines())} lines)"]
    if current == rendered:
        return []
    return list(
        difflib.unified_diff(
            current.splitlines(),
            rendered.splitlines(),
            fromfile=str(path),
            tofile="render",
            lineterm="",
        )
    )


def write_methodology(path: Path, registry: Registry | None = None) -> None:
    """Write the render to ``path`` (LF, UTF-8), creating parent directories."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(render_methodology(registry).encode("utf-8"))
