// web/components/badges.tsx
// Small labelled markers: a judge's status, a search result's entity type,
// a court's type, the actor who took a case action and how much discretion
// the action carried, and the synthetic-data label. Colours carry no
// judgement — a status or an actor is a fact from the source, not a rating.
import { FlaskConical } from "lucide-react";

import { Badge } from "@/components/ui/badge";
import type { ActorType, JudgeStatus, SearchResult } from "@/lib/api/client";
import { titleCase } from "@/lib/format";

type Variant = "default" | "secondary" | "outline" | "destructive";

const STATUS_VARIANT: Record<JudgeStatus, Variant> = {
  active: "default",
  senior: "secondary",
  deceased: "outline",
  retired: "outline",
  resigned: "outline",
  removed: "outline",
  inactive: "outline",
  unknown: "outline",
};

export function StatusBadge({ status }: { status: JudgeStatus }) {
  return (
    <Badge variant={STATUS_VARIANT[status]} data-testid="judge-status">
      {titleCase(status)}
    </Badge>
  );
}

const ENTITY_VARIANT: Record<SearchResult["entity_type"], Variant> = {
  judge: "default",
  court: "secondary",
  case: "outline",
};

export function EntityTypeBadge({ type }: { type: SearchResult["entity_type"] }) {
  return (
    <Badge variant={ENTITY_VARIANT[type]} data-testid="entity-type">
      {titleCase(type)}
    </Badge>
  );
}

export function CourtTypeBadge({ type }: { type: string }) {
  return <Badge variant="outline">{titleCase(type)}</Badge>;
}

/** Every actor the attribution model names, with its display label. */
export const ACTOR_LABELS: Record<ActorType, string> = {
  judge: "Judge",
  prosecutor: "Prosecutor",
  defense: "Defense",
  jury: "Jury",
  clerk: "Clerk",
  law_enforcement: "Law enforcement",
  legislature_or_mandatory_rule: "Mandatory rule",
  appellate_court: "Appellate court",
  unknown: "Unknown actor",
};

// A judicial actor is the only one whose actions enter judge-level metrics,
// so it alone takes the filled variant; every other actor reads as "not the
// judge" at a glance.
const ACTOR_VARIANT: Record<ActorType, Variant> = {
  judge: "default",
  prosecutor: "secondary",
  defense: "secondary",
  jury: "secondary",
  clerk: "outline",
  law_enforcement: "outline",
  legislature_or_mandatory_rule: "outline",
  appellate_court: "secondary",
  unknown: "outline",
};

export function ActorBadge({ actor }: { actor: ActorType }) {
  return (
    <Badge variant={ACTOR_VARIANT[actor]} data-testid="actor-badge" data-actor={actor}>
      {ACTOR_LABELS[actor]}
    </Badge>
  );
}

/** The attribution rule's classification of a decision (case_vocabulary.yaml). */
export const DISCRETION_LABELS: Record<string, string> = {
  discretionary: "Discretionary",
  mandatory: "Mandatory",
  non_judicial: "Non-judicial",
  unknown: "Unclassified",
};

export function DiscretionBadge({ classification }: { classification: string }) {
  return (
    <Badge
      variant="outline"
      data-testid="discretion-badge"
      data-classification={classification}
      title="How the attribution rule classifies the decision"
    >
      {DISCRETION_LABELS[classification] ?? titleCase(classification)}
    </Badge>
  );
}

/**
 * The label every synthetic entity carries. The generator's records are
 * demo data, never court records; the badge says so wherever one appears.
 */
export function SyntheticBadge({ className }: { className?: string }) {
  return (
    <Badge
      variant="outline"
      className={className}
      data-testid="synthetic-badge"
      title="Synthetic demo record generated by JudgeMetrics; not a court record"
    >
      <FlaskConical aria-hidden="true" />
      Synthetic
    </Badge>
  );
}
