/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/courts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List courts */
        get: operations["list_courts_api_v1_courts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/courts/{court_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Court detail with provenance */
        get: operations["get_court_api_v1_courts__court_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/judges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List judges */
        get: operations["list_judges_api_v1_judges_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/judges/{judge_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Judge detail with service records and provenance */
        get: operations["get_judge_api_v1_judges__judge_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/judges/{judge_id}/service": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Service records of a judge, oldest first */
        get: operations["get_judge_service_api_v1_judges__judge_id__service_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jurisdictions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List jurisdictions */
        get: operations["list_jurisdictions_api_v1_jurisdictions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jurisdictions/{jurisdiction_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Jurisdiction detail with provenance */
        get: operations["get_jurisdiction_api_v1_jurisdictions__jurisdiction_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_api_v1_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search judges and courts by name */
        get: operations["search_names_api_v1_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CourtDetail */
        CourtDetail: {
            /** Active From */
            active_from: string | null;
            /** Active To */
            active_to: string | null;
            /** Canonical Name */
            canonical_name: string;
            /**
             * Court Type
             * @description district | appeals | supreme | other (federal, Phase 1).
             */
            court_type: string;
            /** External Ids */
            external_ids: {
                [key: string]: unknown;
            };
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Jurisdiction Id
             * Format: uuid
             */
            jurisdiction_id: string;
            /** Provenance */
            provenance: components["schemas"]["Provenance"][];
            /**
             * State Code
             * @description USPS code parsed from a district-court name.
             */
            state_code: string | null;
        };
        /**
         * CourtRef
         * @description The court a service record belongs to, enough to link and label it.
         */
        CourtRef: {
            /** Canonical Name */
            canonical_name: string;
            /** Court Type */
            court_type: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
        };
        /** CourtSummary */
        CourtSummary: {
            /** Canonical Name */
            canonical_name: string;
            /**
             * Court Type
             * @description district | appeals | supreme | other (federal, Phase 1).
             */
            court_type: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Jurisdiction Id
             * Format: uuid
             */
            jurisdiction_id: string;
            /**
             * State Code
             * @description USPS code parsed from a district-court name.
             */
            state_code: string | null;
        };
        /**
         * ErrorBody
         * @description Every non-2xx response body. Never a stack trace, never SQL.
         */
        ErrorBody: {
            /**
             * Code
             * @description Stable machine-readable code: validation_error, not_found, rate_limited, database_unavailable, internal_error, or http_error.
             */
            code: string;
            /** Message */
            message: string;
            /**
             * Request Id
             * @description Matches the `X-Request-ID` response header.
             */
            request_id: string;
        };
        /** HealthResponse */
        HealthResponse: {
            /** Alembic Head */
            alembic_head: string | null;
            /** Git Sha */
            git_sha: string;
            /**
             * Status
             * @constant
             */
            status: "ok";
            /** Version */
            version: string;
        };
        /** JudgeDetail */
        JudgeDetail: {
            /** Canonical Name */
            canonical_name: string;
            /**
             * External Ids
             * @description Public source identifiers, e.g. `fjc_nid`.
             */
            external_ids: {
                [key: string]: unknown;
            };
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Metadata
             * @description Public biographical facts only.
             */
            metadata: {
                [key: string]: unknown;
            };
            /** Normalized Name */
            normalized_name: string;
            /**
             * Provenance
             * @description The raw artifacts behind this judge and each service record.
             */
            provenance: components["schemas"]["Provenance"][];
            /** Service */
            service: components["schemas"]["ServiceRecord"][];
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "senior" | "deceased" | "retired" | "resigned" | "removed" | "inactive" | "unknown";
        };
        /** JudgeSummary */
        JudgeSummary: {
            /** Canonical Name */
            canonical_name: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "senior" | "deceased" | "retired" | "resigned" | "removed" | "inactive" | "unknown";
        };
        /** JurisdictionDetail */
        JurisdictionDetail: {
            /** Fips Code */
            fips_code: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Parent Jurisdiction Id */
            parent_jurisdiction_id: string | null;
            /** Provenance */
            provenance: components["schemas"]["Provenance"][];
            /** State Code */
            state_code: string | null;
            type: components["schemas"]["JurisdictionType"];
        };
        /** JurisdictionSummary */
        JurisdictionSummary: {
            /** Fips Code */
            fips_code: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Parent Jurisdiction Id */
            parent_jurisdiction_id: string | null;
            /** State Code */
            state_code: string | null;
            type: components["schemas"]["JurisdictionType"];
        };
        /**
         * JurisdictionType
         * @enum {string}
         */
        JurisdictionType: "federal" | "state" | "county" | "city" | "district" | "circuit";
        /** NotReadyResponse */
        NotReadyResponse: {
            /** Reason */
            reason: string;
            /**
             * Status
             * @constant
             */
            status: "not_ready";
        };
        /** Page[CourtSummary] */
        Page_CourtSummary_: {
            /** Items */
            items: components["schemas"]["CourtSummary"][];
            /**
             * Limit
             * @description Page size that was applied.
             */
            limit: number;
            /**
             * Next Offset
             * @description Offset of the next page, or null on the last.
             */
            next_offset: number | null;
            /**
             * Offset
             * @description Rows skipped before this page.
             */
            offset: number;
            /**
             * Total
             * @description Rows matching the filters, across all pages.
             */
            total: number;
        };
        /** Page[JudgeSummary] */
        Page_JudgeSummary_: {
            /** Items */
            items: components["schemas"]["JudgeSummary"][];
            /**
             * Limit
             * @description Page size that was applied.
             */
            limit: number;
            /**
             * Next Offset
             * @description Offset of the next page, or null on the last.
             */
            next_offset: number | null;
            /**
             * Offset
             * @description Rows skipped before this page.
             */
            offset: number;
            /**
             * Total
             * @description Rows matching the filters, across all pages.
             */
            total: number;
        };
        /** Page[JurisdictionSummary] */
        Page_JurisdictionSummary_: {
            /** Items */
            items: components["schemas"]["JurisdictionSummary"][];
            /**
             * Limit
             * @description Page size that was applied.
             */
            limit: number;
            /**
             * Next Offset
             * @description Offset of the next page, or null on the last.
             */
            next_offset: number | null;
            /**
             * Offset
             * @description Rows skipped before this page.
             */
            offset: number;
            /**
             * Total
             * @description Rows matching the filters, across all pages.
             */
            total: number;
        };
        /**
         * Provenance
         * @description Where a row's current values came from: one retrieved raw artifact.
         *
         *     The raw object itself lives in the immutable lake under an internal
         *     storage key that is never published; ``raw_sha256`` identifies its
         *     bytes and ``ingest_run_id`` the run that fetched it.
         */
        Provenance: {
            /**
             * External Record Id
             * @description The artifact's id at the source.
             */
            external_record_id: string | null;
            /**
             * Ingest Run Id
             * Format: uuid
             */
            ingest_run_id: string;
            /** Parser Version */
            parser_version: string;
            /** Raw Sha256 */
            raw_sha256: string;
            /**
             * Retrieved At
             * Format: date-time
             */
            retrieved_at: string;
            /**
             * Source
             * @description Source register key (docs/DATA_SOURCES.md), e.g. `fjc`.
             */
            source: string;
        };
        /** ReadyResponse */
        ReadyResponse: {
            /** Alembic Current */
            alembic_current: string | null;
            /**
             * Database
             * @constant
             */
            database: "ok";
            /**
             * Status
             * @constant
             */
            status: "ready";
        };
        /** SearchResponse */
        SearchResponse: {
            /**
             * Items
             * @description Best matches first.
             */
            items: components["schemas"]["SearchResult"][];
            /** Limit */
            limit: number;
            /**
             * Query
             * @description The query after name normalization, as matched.
             */
            query: string;
        };
        /** SearchResult */
        SearchResult: {
            /**
             * Entity Type
             * @enum {string}
             */
            entity_type: "judge" | "court";
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Score
             * @description pg_trgm similarity to the query.
             */
            score: number;
        };
        /**
         * ServiceRecord
         * @description One appointment: a judge at a court in a position over an interval.
         */
        ServiceRecord: {
            court: components["schemas"]["CourtRef"];
            /**
             * End Date
             * @description Null while the appointment is current.
             */
            end_date: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Metadata
             * @description Public appointment facts with no column of their own.
             */
            metadata: {
                [key: string]: unknown;
            };
            /** Position Type */
            position_type: string;
            /** Start Date */
            start_date: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_courts_api_v1_courts_get: {
        parameters: {
            query?: {
                /** @description Only courts of this jurisdiction. */
                jurisdiction_id?: string | null;
                /** @description Exact court type: district, appeals, supreme, other (federal, Phase 1). */
                court_type?: string | null;
                /** @description Page size, at most 100. */
                limit?: number;
                /** @description Rows to skip. */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_CourtSummary_"];
                };
            };
            /** @description A parameter is invalid, or a query parameter is not one the route declares. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_court_api_v1_courts__court_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                court_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourtDetail"];
                };
            };
            /** @description The resource does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description A parameter is invalid, or a query parameter is not one the route declares. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_judges_api_v1_judges_get: {
        parameters: {
            query?: {
                /** @description Name to match by trigram similarity (normalized before matching). */
                q?: string | null;
                /** @description Only judges with a service record at this court. */
                court_id?: string | null;
                /** @description Only judges whose service interval covers this date (ISO 8601). */
                active_on?: string | null;
                /** @description Exact status. */
                status?: ("active" | "senior" | "deceased" | "retired" | "resigned" | "removed" | "inactive" | "unknown") | null;
                /** @description Page size, at most 100. */
                limit?: number;
                /** @description Rows to skip. */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_JudgeSummary_"];
                };
            };
            /** @description A parameter is invalid, or a query parameter is not one the route declares. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_judge_api_v1_judges__judge_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                judge_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JudgeDetail"];
                };
            };
            /** @description The resource does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description A parameter is invalid, or a query parameter is not one the route declares. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_judge_service_api_v1_judges__judge_id__service_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                judge_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceRecord"][];
                };
            };
            /** @description The resource does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description A parameter is invalid, or a query parameter is not one the route declares. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_jurisdictions_api_v1_jurisdictions_get: {
        parameters: {
            query?: {
                /** @description Page size, at most 100. */
                limit?: number;
                /** @description Rows to skip. */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_JurisdictionSummary_"];
                };
            };
            /** @description A parameter is invalid, or a query parameter is not one the route declares. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_jurisdiction_api_v1_jurisdictions__jurisdiction_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jurisdiction_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JurisdictionDetail"];
                };
            };
            /** @description The resource does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description A parameter is invalid, or a query parameter is not one the route declares. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    ready_api_v1_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotReadyResponse"];
                };
            };
        };
    };
    search_names_api_v1_search_get: {
        parameters: {
            query: {
                /** @description Name to match; normalized like judge names before matching. */
                q: string;
                /** @description Results to return, at most 100. */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description A parameter is invalid, or a query parameter is not one the route declares. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Rate limit exceeded; `Retry-After` gives the wait in seconds. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
}
