# src/judgemetrics/validation/report.py
"""``docs/VALIDATION.md``: the validation of the expected-outcome models, rendered.

``build_report(session, settings, truth_dir=)`` assembles a
``ValidationReport`` from the latest snapshot's fitted models (as the
ingest role: the subgroup calibration reads the restricted schema): per
source, the dataset (register name, coverage window, the frame's row counts,
and — for a synthetic source whose manifest the truth directory holds — the
manifest's seed, scale, generator and truth versions); per model, the
temporal-split diagnostics (Brier score and skill, ROC AUC, calibration in
the large, slope, the ten calibration bins), the observed rate and the mean
prediction per calendar year, and the coefficients' bootstrap stability;
the missing-data sensitivity, the bootstrap stability of the judge-level
estimates, the subgroup calibration, and the recovery of the planted
effects. ``render_report(report)`` turns it into Markdown wrapped at 80
columns. Nothing in it is a UUID, a hash, a judge's name or code, a code
version, a timestamp of a run, or a local path, and every list has an order
the data alone fixes (specification order, vocabulary order, calendar
order), so the same dataset renders the same document in any database.
``check_report`` and ``write_report`` follow ``methodology render``: a
relative path is resolved under the repository root.
"""

from __future__ import annotations

import difflib
import textwrap
import uuid
from collections.abc import Iterable, Mapping, Sequence
from dataclasses import dataclass
from datetime import date
from pathlib import Path
from typing import Any

import numpy as np
from sqlalchemy.orm import Session

from judgemetrics.config import Settings
from judgemetrics.db.models import SYNTHETIC_SOURCE_TYPE
from judgemetrics.metrics.adjustment.artifacts import ArtifactError
from judgemetrics.metrics.adjustment.catalog import CatalogError, resolve_snapshot
from judgemetrics.metrics.adjustment.diagnostics import CalibrationBin, split_cutoff
from judgemetrics.metrics.adjustment.features import instant
from judgemetrics.metrics.adjustment.logistic import predict
from judgemetrics.metrics.adjustment.spec import OutcomeModelSpec, load_spec
from judgemetrics.metrics.registry import Registry, load_registry
from judgemetrics.metrics.snapshot import open_snapshot
from judgemetrics.validation.fairness import SubgroupCell, subgroup_calibration
from judgemetrics.validation.inputs import InputError, ModelInput, SourceInput, load_inputs
from judgemetrics.validation.recovery import (
    RecoveryResult,
    Truth,
    TruthError,
    database_recovery,
    read_truth,
    truth_matches,
)
from judgemetrics.validation.sensitivity import Sensitivity, missing_data_sensitivity
from judgemetrics.validation.stability import (
    BootstrapStability,
    CoefficientStability,
    Spread,
    bootstrap_stability,
    coefficient_stability,
)

DEFAULT_OUTPUT = Path("docs") / "VALIDATION.md"
WIDTH = 80
PATH_COMMENT = "<!-- docs/VALIDATION.md -->"
GENERATED_NOTICE = (
    "<!-- Generated by `judgemetrics validation report` from the latest metric\n"
    "     snapshot's expected-outcome models. Do not edit by hand: re-render. -->"
)
DASH = "-"
# The frame tables whose row counts describe a source's dataset, in this order.
ROW_TABLES: tuple[str, ...] = (
    "cases",
    "charges",
    "assignments",
    "decisions",
    "sentences",
    "events",
    "justice_events",
    "persons",
    "courts",
)
# The brief's <risk_adjustment><interpretation>, verbatim.
INTERPRETATION = (
    "An O/E ratio above 1 means observed outcomes exceeded the model's expected count for "
    "the defined cohort. A ratio below 1 means observed outcomes were below the model's "
    "expected count. It must not be described as proof that the judge caused the difference."
)
WITHHELD_TEXT: Mapping[str, str] = {
    "below_threshold": "withheld: too few events",
    "expected_below_minimum": "withheld: E too small",
    "model_unavailable": "withheld: no model",
}


class ReportError(RuntimeError):
    """The report cannot be assembled (no snapshot, no model, an unreadable truth)."""


# --- the report's data ----------------------------------------------------------------------


@dataclass(frozen=True, slots=True)
class DatasetSummary:
    """One source's dataset as the report names it (never by a path)."""

    source: str
    synthetic: bool
    coverage_start: date | None
    coverage_end: date | None
    rows: tuple[tuple[str, int], ...]
    seed: int | None = None
    scale: str | None = None
    generator_version: str | None = None
    truth_version: str | None = None
    # (target, window, reason) of every target the source cannot support (spec 3).
    unavailable: tuple[tuple[str, int | None, str], ...] = ()


@dataclass(frozen=True, slots=True)
class YearRow:
    """One calendar year of a model's index events: the observed rate and the mean prediction."""

    year: int
    events: int
    observed_rate: float
    mean_predicted: float | None
    split: str  # "train", "test", or "both" (the year straddles the temporal split's cutoff)


@dataclass(frozen=True, slots=True)
class ModelSummary:
    """One model's fit, temporal-split diagnostics, and coefficient stability."""

    source: str
    target: str
    window_days: int | None
    status: str
    rows: int
    events: int
    eligible: int
    excluded_missing: int
    n_train: int
    events_train: int
    n_test: int
    events_test: int
    temporal_status: str | None
    base_rate_train: float | None
    brier: float | None
    brier_skill: float | None
    auc: float | None
    calibration_in_the_large: float | None
    calibration_slope: float | None
    bins: tuple[CalibrationBin, ...]
    years: tuple[YearRow, ...]
    coefficients: tuple[CoefficientStability, ...]


@dataclass(frozen=True, slots=True)
class ReportSettings:
    """The specification values the report states beside its figures."""

    spec_version: int
    model_version: str
    registry_version: int
    methodology_version: str
    minimum_cohort: int
    minimum_expected: float
    minimum_events_per_column: int
    replicates: int
    level: float
    test_quantile: float


@dataclass(frozen=True, slots=True)
class ValidationReport:
    """Everything ``render_report`` prints."""

    settings: ReportSettings
    datasets: tuple[DatasetSummary, ...]
    models: tuple[ModelSummary, ...]
    sensitivity: tuple[Sensitivity, ...]
    stability: tuple[BootstrapStability, ...]
    subgroups: tuple[SubgroupCell, ...]
    recovery: tuple[RecoveryResult, ...]

    @property
    def synthetic(self) -> bool:
        return any(dataset.synthetic for dataset in self.datasets)


# --- assembling -----------------------------------------------------------------------------


def _float(value: Any) -> float | None:
    return None if value is None else float(value)


def _bins(diagnostics: Mapping[str, Any]) -> tuple[CalibrationBin, ...]:
    return tuple(
        CalibrationBin(
            bin=int(item["bin"]),
            count=int(item["count"]),
            mean_predicted=_float(item.get("mean_predicted")),
            observed_rate=_float(item.get("observed_rate")),
        )
        for item in diagnostics.get("bins") or ()
    )


def year_rows(model: ModelInput, spec: OutcomeModelSpec) -> tuple[YearRow, ...]:
    """Per calendar year of the index events: count, observed rate, mean published prediction."""
    design = model.design
    if not design.rows:
        return ()
    years = np.array([instant(int(value)).year for value in design.index_at], dtype=np.int64)
    parameters = model.parameters
    predicted = (
        predict(parameters.coefficients, design.matrix)
        if parameters.fitted and parameters.coefficients is not None
        else None
    )
    cutoff = split_cutoff(design.index_at, spec.temporal_split.test_quantile)
    rows: list[YearRow] = []
    for year in sorted({int(value) for value in years}):
        members = years == year
        if cutoff is None:
            split = "train"
        else:
            after = design.index_at[members] >= cutoff
            split = "test" if after.all() else "train" if not after.any() else "both"
        rows.append(
            YearRow(
                year=year,
                events=int(members.sum()),
                observed_rate=float(design.outcome[members].mean()),
                mean_predicted=None if predicted is None else float(predicted[members].mean()),
                split=split,
            )
        )
    return tuple(rows)


def model_summary(model: ModelInput, spec: OutcomeModelSpec) -> ModelSummary:
    diagnostics = model.diagnostics
    design = model.design
    return ModelSummary(
        source=model.source,
        target=model.target.name,
        window_days=model.window_days,
        status=model.status,
        rows=design.rows,
        events=design.events,
        eligible=design.eligible,
        excluded_missing=design.excluded_missing,
        n_train=model.n_train,
        events_train=model.events_train,
        n_test=model.n_test,
        events_test=model.events_test,
        temporal_status=None if not diagnostics else str(diagnostics.get("status")),
        base_rate_train=_float(diagnostics.get("base_rate_train")),
        brier=_float(diagnostics.get("brier")),
        brier_skill=_float(diagnostics.get("brier_skill")),
        auc=_float(diagnostics.get("auc")),
        calibration_in_the_large=_float(diagnostics.get("calibration_in_the_large")),
        calibration_slope=_float(diagnostics.get("calibration_slope")),
        bins=_bins(diagnostics),
        years=year_rows(model, spec),
        coefficients=coefficient_stability(model),
    )


def dataset_summary(item: SourceInput, truth: Truth | None) -> DatasetSummary:
    frame = item.frame
    rows = tuple((name, int(getattr(frame, name).height)) for name in ROW_TABLES)
    return DatasetSummary(
        source=item.source.name,
        synthetic=item.source.source_type == SYNTHETIC_SOURCE_TYPE,
        coverage_start=item.source.coverage_start,
        coverage_end=item.source.coverage_end,
        rows=rows,
        seed=None if truth is None else truth.seed,
        scale=None if truth is None else truth.scale,
        generator_version=None if truth is None else truth.generator_version,
        truth_version=None if truth is None else truth.truth_version,
        unavailable=item.unavailable,
    )


def report_settings(spec: OutcomeModelSpec, registry: Registry) -> ReportSettings:
    return ReportSettings(
        spec_version=spec.version,
        model_version=spec.model_version,
        registry_version=registry.version,
        methodology_version=registry.methodology_version,
        minimum_cohort=spec.thresholds.minimum_cohort,
        minimum_expected=spec.thresholds.minimum_expected,
        minimum_events_per_column=spec.thresholds.minimum_events_per_column,
        replicates=spec.bootstrap.replicates,
        level=spec.bootstrap.level,
        test_quantile=spec.temporal_split.test_quantile,
    )


def build_report(
    session: Session,
    settings: Settings,
    *,
    truth_dir: Path | None,
    spec: OutcomeModelSpec | None = None,
    registry: Registry | None = None,
    sources: Sequence[str] | None = None,
) -> ValidationReport:
    """The report of the latest snapshot's models (the caller's session is the ingest role's).

    ``sources`` (register names) selects the sources; by default every source
    with a model whose fit was attempted (``inputs.load_inputs``).
    """
    spec = spec or load_spec()
    registry = registry or load_registry()
    try:
        snapshot_row = resolve_snapshot(session, None)
    except CatalogError as exc:
        raise ReportError(str(exc)) from exc
    truth: Truth | None = None
    if truth_dir is not None and truth_dir.exists():
        try:
            truth = read_truth(truth_dir)
        except TruthError as exc:
            raise ReportError(f"--truth: {exc}") from exc
    with open_snapshot(settings, snapshot_row.content_hash) as snapshot:
        try:
            inputs = load_inputs(
                session, settings, snapshot, snapshot_row.id, spec=spec, sources=sources
            )
        except (InputError, ArtifactError) as exc:
            raise ReportError(str(exc)) from exc
        models = [model for item in inputs for model in item.models]
        datasets: list[DatasetSummary] = []
        recovery: list[RecoveryResult] = []
        for item in inputs:
            matched: Truth | None = None
            if (
                truth is not None
                and item.source.source_type == SYNTHETIC_SOURCE_TYPE
                and truth_matches(session, uuid.UUID(item.source.id), truth)
            ):
                matched = truth
                recovery.extend(
                    database_recovery(
                        session,
                        source_id=uuid.UUID(item.source.id),
                        snapshot_id=snapshot_row.id,
                        truth=truth,
                        spec=spec,
                        registry=registry,
                    )
                )
            datasets.append(dataset_summary(item, matched))
        synthetic = [dataset for dataset in datasets if dataset.synthetic]
        if truth is not None and synthetic and not any(d.seed is not None for d in synthetic):
            # A truth beside a synthetic source it does not describe is refused; a
            # database without a synthetic source has nothing to recover.
            msg = "--truth: its manifest.json is not the one any synthetic source ingested"
            raise ReportError(msg)
        subgroups = subgroup_calibration(session, snapshot, models, settings=settings, spec=spec)
        return ValidationReport(
            settings=report_settings(spec, registry),
            datasets=tuple(datasets),
            models=tuple(model_summary(model, spec) for model in models),
            sensitivity=tuple(missing_data_sensitivity(model, spec) for model in models),
            stability=tuple(bootstrap_stability(model, spec) for model in models),
            subgroups=tuple(subgroups),
            recovery=tuple(recovery),
        )


# --- rendering ------------------------------------------------------------------------------


def _fill(text: str) -> str:
    return textwrap.fill(text, width=WIDTH, break_long_words=False, break_on_hyphens=False)


def _bullet(text: str) -> str:
    return textwrap.fill(
        text,
        width=WIDTH,
        initial_indent="- ",
        subsequent_indent="  ",
        break_long_words=False,
        break_on_hyphens=False,
    )


def fmt(value: float | None, digits: int = 3) -> str:
    """A figure at ``digits`` decimals (no negative zero); a dash when absent."""
    if value is None or not np.isfinite(value):
        return DASH
    text = f"{value:.{digits}f}"
    return text[1:] if text.startswith("-") and float(text) == 0.0 else text


def _window(window: int | None) -> str:
    return DASH if window is None else str(window)


def _model_heading(source: str, target: str, window: int | None) -> str:
    suffix = "" if window is None else f", {window} days"
    return f"### {source}: {target}{suffix}"


def _table(header: Sequence[str], rows: Iterable[Sequence[str]]) -> list[str]:
    lines = ["| " + " | ".join(header) + " |", "|" + "|".join("---" for _ in header) + "|"]
    lines.extend("| " + " | ".join(row) + " |" for row in rows)
    return lines


def _paragraphs(*texts: str) -> list[str]:
    lines: list[str] = []
    for text in texts:
        lines.extend([_fill(text), ""])
    return lines


def _median(spread: Spread | None, digits: int = 3) -> str:
    return DASH if spread is None else fmt(spread.median, digits)


def _quartiles(spread: Spread | None, digits: int = 3) -> str:
    return DASH if spread is None else f"{fmt(spread.p25, digits)}-{fmt(spread.p75, digits)}"


def _section_header(report: ValidationReport) -> list[str]:
    lines = [PATH_COMMENT, GENERATED_NOTICE, "# Validation of the expected-outcome models", ""]
    if report.synthetic:
        lines.extend(
            _paragraphs(
                "**Synthetic data.** Every figure in this report is computed from a "
                "labelled synthetic dataset generated by JudgeMetrics itself: no court, "
                "judge, or person in it is real, and the figures describe the generator, "
                "not any justice system."
            )
        )
    lines.extend(
        _paragraphs(
            "This report validates the expected-outcome models behind every "
            "observed-to-expected ratio against the brief's model-validation tests: the "
            "temporal train/test split, calibration curves, the Brier score, ROC AUC as a "
            "secondary diagnostic, subgroup calibration, feature stability, missing-data "
            "sensitivity, and the bootstrap stability of the judge-level estimates. It is "
            "rendered by `judgemetrics validation report` and checked in CI with `--check`; "
            "the methodology is docs/METHODOLOGY.md.",
            "These statistics describe associations in available records. They do not "
            "prove that a judicial decision caused a later event. " + INTERPRETATION,
        )
    )
    return lines


def _section_dataset(report: ValidationReport) -> list[str]:
    settings = report.settings
    lines = ["## Dataset and versions", ""]
    for dataset in report.datasets:
        kind = "synthetic" if dataset.synthetic else "recorded"
        coverage = (
            "no coverage window"
            if dataset.coverage_start is None or dataset.coverage_end is None
            else f"coverage {dataset.coverage_start.isoformat()} to "
            f"{dataset.coverage_end.isoformat()}"
        )
        manifest = (
            ""
            if dataset.seed is None
            else f"; manifest seed {dataset.seed}, scale {dataset.scale}, generator version "
            f"{dataset.generator_version}, truth version {dataset.truth_version}"
        )
        lines.append(_bullet(f"Source `{dataset.source}` ({kind} data): {coverage}{manifest}."))
        counts = ", ".join(f"{name} {count}" for name, count in dataset.rows)
        lines.append(_bullet(f"Rows in the snapshot's frame of `{dataset.source}`: {counts}."))
        grouped: dict[tuple[str, str], list[int]] = {}
        for target, window, reason in dataset.unavailable:
            windows = grouped.setdefault((target, reason), [])
            if window is not None:
                windows.append(window)
        for (target, reason), windows in grouped.items():
            suffix = "" if not windows else f" (windows {', '.join(map(str, windows))} days)"
            lines.append(
                _bullet(
                    f"Target `{target}`{suffix} is unavailable for `{dataset.source}`: {reason}"
                )
            )
    lines.append(
        _bullet(
            f"Outcome model specification version {settings.spec_version} "
            f"(`{settings.model_version}`); metric registry version "
            f"{settings.registry_version}; methodology version {settings.methodology_version}."
        )
    )
    lines.append(
        _bullet(
            f"Thresholds: a model is fitted when its limiting class has at least "
            f"{settings.minimum_events_per_column} events per design column; a judge's ratio "
            f"and a subgroup cell are published with at least {settings.minimum_cohort} index "
            f"events and {fmt(settings.minimum_expected, 0)} expected events; "
            f"{settings.replicates} person-cluster bootstrap replicates; "
            f"{fmt(settings.level * 100, 0)}% percentile intervals; the temporal split's test "
            f"set is the index events at or after the {fmt(settings.test_quantile, 2)} "
            "quantile of index time."
        )
    )
    lines.append("")
    return lines


def _section_summary(report: ValidationReport) -> list[str]:
    lines = ["## Summary", ""]
    lines.extend(
        _paragraphs(
            "Per target and window: the model's status, its index events (n) and outcomes "
            "(O), and the temporal split's training and test rows and outcomes. The "
            "diagnostics are measured on the test set, scored by a model refitted on the "
            "training set alone (a calendar year unseen in training is scored at the last "
            "training year's level): the Brier score and its skill against the training "
            "base rate, ROC AUC, calibration in the large (observed over expected), and the "
            "calibration slope (1 for a calibrated model)."
        )
    )
    lines.extend(
        _table(
            ("Target", "Window", "Status", "n", "O", "Train n", "Train O", "Test n", "Test O"),
            (
                (
                    m.target,
                    _window(m.window_days),
                    m.status,
                    str(m.rows),
                    str(m.events),
                    str(m.n_train),
                    str(m.events_train),
                    str(m.n_test),
                    str(m.events_test),
                )
                for m in report.models
            ),
        )
    )
    lines.append("")
    lines.extend(
        _table(
            ("Target", "Window", "Brier", "Skill", "AUC", "O/E (test)", "Slope"),
            (
                (
                    m.target,
                    _window(m.window_days),
                    fmt(m.brier),
                    fmt(m.brier_skill),
                    fmt(m.auc),
                    fmt(m.calibration_in_the_large),
                    fmt(m.calibration_slope),
                )
                for m in report.models
            ),
        )
    )
    lines.append("")
    return lines


def _section_calibration(report: ValidationReport) -> list[str]:
    lines = ["## Calibration", ""]
    lines.extend(
        _paragraphs(
            "The test set ordered by predicted probability and cut into ten equal-count "
            "bins: per bin the rows, the mean prediction, and the observed rate. A "
            "calibrated model's two columns agree."
        )
    )
    for m in report.models:
        lines.extend([_model_heading(m.source, m.target, m.window_days), ""])
        if not m.bins:
            lines.extend(_paragraphs(f"No temporal-split fit ({m.temporal_status or m.status})."))
            continue
        lines.extend(
            _table(
                ("Bin", "Rows", "Mean predicted", "Observed rate"),
                (
                    (str(b.bin), str(b.count), fmt(b.mean_predicted), fmt(b.observed_rate))
                    for b in m.bins
                ),
            )
        )
        lines.append("")
    return lines


def _section_temporal(report: ValidationReport) -> list[str]:
    lines = ["## Temporal transport", ""]
    texts = [
        "Per calendar year of the index event: the index events, the observed rate, the "
        "mean prediction of the published fit (which carries the calendar-year feature, so "
        "within a year the two agree up to the penalty), and the side of the temporal "
        "split the year falls on. The split's test years are unseen in training and are "
        "scored at the last training year's level, so a trend in the observed rate across "
        "years appears in the summary as calibration in the large away from 1, a slope "
        "below 1, and a low test AUC, while the published fit absorbs the trend.",
    ]
    if report.synthetic:
        texts.append(
            'For the synthetic source, docs/SYNTHETIC_DATA.md "Temporal transport" '
            "explains the trend the generator produces in the new-case rate."
        )
    lines.extend(_paragraphs(*texts))
    for m in report.models:
        lines.extend([_model_heading(m.source, m.target, m.window_days), ""])
        if not m.years:
            lines.extend(_paragraphs("No index events."))
            continue
        lines.extend(
            _table(
                ("Year", "Index events", "Observed rate", "Mean predicted", "Split"),
                (
                    (
                        str(y.year),
                        str(y.events),
                        fmt(y.observed_rate),
                        fmt(y.mean_predicted),
                        y.split,
                    )
                    for y in m.years
                ),
            )
        )
        lines.append("")
    return lines


def _section_features(report: ValidationReport) -> list[str]:
    lines = ["## Feature stability", ""]
    lines.extend(
        _paragraphs(
            "Per design column of the published fit (a feature at a level, against the "
            "feature's reference; a court, jurisdiction, or year by its rank label or year, "
            "never by an identifier): the estimate, the standard deviation over the "
            "converged bootstrap replicates, and the share of replicates agreeing with the "
            "estimate in sign. A share near 0.5 means the data cannot tell the column's "
            "direction."
        )
    )
    for m in report.models:
        lines.extend([_model_heading(m.source, m.target, m.window_days), ""])
        if not m.coefficients:
            lines.extend(_paragraphs(f"No published fit ({m.status})."))
            continue
        lines.extend(
            _table(
                ("Column", "Estimate", "SD", "Sign agreement"),
                (
                    (c.column, fmt(c.estimate), fmt(c.sd), fmt(c.sign_agreement))
                    for c in m.coefficients
                ),
            )
        )
        lines.append("")
    return lines


def _section_sensitivity(report: ValidationReport) -> list[str]:
    lines = ["## Missing-data sensitivity", ""]
    lines.extend(
        _paragraphs(
            "Each model refitted without every index event that has a feature at its "
            "missing level (complete cases), both fits scoring every row of the design so "
            "each judge's cohort is unchanged; across the judges whose ratio is published, "
            "the Spearman correlation of the two fits' pooled ratios and the largest "
            "absolute change (max change). Excluded: eligible events dropped before the "
            "design under a feature's exclude rule. Missing: design rows with a feature at "
            "its missing level, which the complete-case refit drops."
        )
    )
    lines.extend(
        _table(
            (
                "Target",
                "Window",
                "Rows",
                "Excluded",
                "Missing",
                "Judges",
                "Spearman",
                "Max change",
            ),
            (
                (
                    s.target,
                    _window(s.window_days),
                    str(s.rows),
                    str(s.excluded_missing),
                    str(s.at_missing_level),
                    str(s.judges),
                    fmt(s.spearman),
                    fmt(s.max_abs_change, 4),
                )
                if s.status == "compared"
                else (
                    s.target,
                    _window(s.window_days),
                    str(s.rows),
                    str(s.excluded_missing),
                    str(s.at_missing_level),
                    str(s.judges),
                    DASH,
                    s.status,
                )
                for s in report.sensitivity
            ),
        )
    )
    lines.append("")
    return lines


def _section_bootstrap(report: ValidationReport) -> list[str]:
    lines = ["## Bootstrap stability of the judge-level estimates", ""]
    lines.extend(
        _paragraphs(
            "Over the judges whose ratio is published, as distributions (median and "
            "quartiles), never per judge: the width of the 95% percentile interval of the "
            "pooled ratio (median and interquartile range), the share of those intervals "
            "that exclude 1, and the width of "
            "each judge's 95% rank interval (the judges ranked by pooled ratio within every "
            "replicate). The interval is the bootstrap distribution of the pooled estimate, "
            "which is shrunk toward 1: it describes that estimate's sampling variability, "
            "not a confidence interval for the judge's true ratio.",
        )
    )
    lines.extend(
        _table(
            ("Target", "Window", "Replicates", "Judges", "Median width", "IQR", "Excl. 1"),
            (
                (
                    b.target,
                    _window(b.window_days),
                    f"{b.replicates}/{b.requested}",
                    str(b.judges),
                    _median(b.interval_width),
                    _quartiles(b.interval_width),
                    fmt(b.share_excluding_one),
                )
                for b in report.stability
            ),
        )
    )
    lines.append("")
    lines.extend(
        _table(
            ("Target", "Window", "Judges", "Median rank width", "IQR"),
            (
                (
                    b.target,
                    _window(b.window_days),
                    str(b.judges),
                    _median(b.rank_width, 1),
                    _quartiles(b.rank_width, 1),
                )
                for b in report.stability
            ),
        )
    )
    lines.append("")
    return lines


def _section_subgroups(report: ValidationReport) -> list[str]:
    settings = report.settings
    lines = ["## Subgroup calibration", ""]
    texts = [
        "Per model and restricted attribute value, aggregated over the index events: the "
        "events, the observed outcomes (O), the expected count from the published model "
        "(E), O/E, and its 95% percentile interval over the bootstrap replicates. The model "
        "never reads a restricted attribute (the specification excludes them by policy); "
        "this table shows what that choice leaves in the residual. A cell with fewer than "
        f"{settings.minimum_cohort} index events or {fmt(settings.minimum_expected, 0)} "
        "expected events, or without a fitted model, is withheld with its reason and shows "
        "no figure. The attributes are read from the restricted schema by one module, as "
        "the ingest role, and never leave it below the aggregate.",
    ]
    if report.synthetic:
        texts.append(
            "On the synthetic source the two attributes are controls. The filing-age band "
            "is the positive control: the generator moves the failure-to-appear log-odds "
            "and the next-filing exponent by band, and the model omits it, so its cells "
            "must show the planted direction (younger bands above 1, older below). The "
            "synthetic group is the negative control: drawn on its own stream and read by "
            "no draw, so every one of its cells must be calibrated (O/E near 1)."
        )
    lines.extend(_paragraphs(*texts))
    keys: list[tuple[str, str, int | None]] = []
    for cell in report.subgroups:
        key = (cell.source, cell.target, cell.window_days)
        if key not in keys:
            keys.append(key)
    for source, target, window in keys:
        lines.extend([_model_heading(source, target, window), ""])
        cells = [
            c
            for c in report.subgroups
            if (c.source, c.target, c.window_days) == (source, target, window)
        ]
        lines.extend(
            _table(
                ("Attribute", "Value", "Events", "O", "E", "O/E", "95% interval"),
                (
                    (
                        c.attribute,
                        c.value,
                        str(c.events),
                        str(c.observed),
                        fmt(c.expected, 1),
                        fmt(c.ratio),
                        f"{fmt(c.lower)}-{fmt(c.upper)}",
                    )
                    if c.withheld is None
                    else (
                        c.attribute,
                        c.value,
                        DASH,
                        DASH,
                        DASH,
                        DASH,
                        WITHHELD_TEXT.get(c.withheld, f"withheld: {c.withheld}"),
                    )
                    for c in cells
                ),
            )
        )
        lines.append("")
    return lines


def _section_recovery(report: ValidationReport) -> list[str]:
    lines = ["## Recovery of the planted effects", ""]
    if not report.recovery:
        lines.extend(
            _paragraphs(
                "No source of this snapshot is a synthetic dataset whose truth directory "
                "was given, so there is no planted answer to recover."
            )
        )
        return lines
    lines.extend(
        _paragraphs(
            "On the database path - after ingest, entity resolution, the snapshot, and the "
            "compute - the published pooled ratios of the judges with at least the "
            "specification's minimum followed cohort, against the synthetic truth: the "
            "Spearman correlation of the log pooled ratio with the court-centered planted "
            "effect (raw: the raw rates' correlation, for contrast), the sign agreement over "
            "the judges whose centered effect exceeds the threshold, the Pearson correlation "
            "of the expected counts with the oracle's, and the share of published intervals "
            "covering the true ratio, each against the specification's recovery block.",
        )
    )
    for r in report.recovery:
        window = "" if r.window_days is None else f", {r.window_days} days"
        if r.spearman is None:
            lines.append(
                _bullet(
                    f"`{r.target}`{window}: {r.judges} judges with a published ratio and at "
                    "least the minimum cohort, too few to evaluate: not met."
                )
            )
            continue
        lines.append(
            _bullet(
                f"`{r.target}`{window}: {r.judges} judges; Spearman {fmt(r.spearman)} "
                f"(minimum {fmt(r.spearman_minimum, 2)}; raw rates {fmt(r.raw_spearman)}); "
                f"sign agreed for {r.sign_agreed} of the {r.sign_checked} judges whose "
                f"centered effect exceeds {fmt(r.sign_threshold, 2)}; expected-count "
                f"correlation {fmt(r.expected_correlation)} (minimum "
                f"{fmt(r.expected_minimum, 2)}); interval coverage {fmt(r.coverage)} "
                f"(minimum {fmt(r.coverage_minimum, 2)}): " + ("met." if r.passed else "not met.")
            )
        )
    lines.append("")
    return lines


def _section_limitations() -> list[str]:
    return [
        "## Limitations",
        "",
        *_paragraphs(
            "The limitations of adjustment (unobserved confounding, model misspecification, "
            "the restricted attributes excluded by policy, intervals conditional on the "
            'specification) are stated under "Adjusted statistics" in docs/METHODOLOGY.md, '
            'and the brief\'s statistical warnings under "Known limitations" there; they '
            "apply to every figure in this report."
        ),
    ]


def render_report(report: ValidationReport) -> str:
    """The Markdown document (LF line endings, one trailing newline, 80 columns)."""
    lines: list[str] = []
    for section in (
        _section_header(report),
        _section_dataset(report),
        _section_summary(report),
        _section_calibration(report),
        _section_temporal(report),
        _section_features(report),
        _section_sensitivity(report),
        _section_bootstrap(report),
        _section_subgroups(report),
        _section_recovery(report),
        _section_limitations(),
    ):
        lines.extend(section)
    return "\n".join(lines).rstrip("\n") + "\n"


def check_report(path: Path, rendered: str) -> list[str]:
    """The unified diff between the file at ``path`` and ``rendered``; empty when equal."""
    try:
        current = path.read_bytes().decode("utf-8")
    except FileNotFoundError:
        return [f"--- {path} is missing", f"+++ render ({len(rendered.splitlines())} lines)"]
    if current == rendered:
        return []
    return list(
        difflib.unified_diff(
            current.splitlines(),
            rendered.splitlines(),
            fromfile=str(path),
            tofile="render",
            lineterm="",
        )
    )


def write_report(path: Path, rendered: str) -> None:
    """Write ``rendered`` to ``path`` (LF, UTF-8), creating parent directories."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(rendered.encode("utf-8"))
