# src/judgemetrics/ingest/cook_sao/profile.py
"""The value-set profile of the Cook County exports (``data/reference/cook_sao/profile.yaml``).

``build_profile`` scans each of the five stored exports lazily with Polars,
every column a string (``infer_schema=False``; an empty field, quoted or
not, is null), and returns a plain mapping that ``render_profile`` writes
with ``yaml.safe_dump`` and sorted keys under a fixed header. The same
artifacts always render the same bytes: nothing reads the clock, every
list has a data-fixed order (value sets by count, then value), and the
artifacts' record facts (rows-updated and retrieval times) come from the
``source_record`` rows, not from the run. The profile is regenerated,
never hand-edited; ``check_profile`` is ``--check``'s diff.

What it records (``PROFILE_VERSION`` 1):

- ``artifacts`` — external id, sha256, bytes, rows updated, retrieved at.
- ``datasets.<file>`` — the row count; per column the null count and,
  by class (``schema``): a coded or judge column's distinct values with
  counts, ordered by count and then value; a date column's values per
  format (``schema.DATE_FORMATS``), its range, the values carrying a time
  other than midnight, and the values in neither format; a numeric column's range (identifiers excepted)
  and unparseable values; race and gender as their distinct values only
  (no count, no null count); the age's range and nulls only; every other
  column its distinct count only. Plus the (disposition, reason) pairs
  with counts.
- ``keys`` — per dataset the distinct cases, participants, and (case,
  participant) keys, the participants under more than one case (the
  cross-case measurement), and the participants per case; the share of
  each dataset's keys found in Intake and the participants found there
  under another case; per charge-bearing dataset the charge ids, the
  versions per charge, the charge ids under more than one case and the
  versions under more than one charge; in Initiation the rows and
  participants per charge version; in Dispositions and Sentencing the
  rows per charge version and per participant.
- ``anomalies`` — rows received before 2011-01-01 with the earliest
  dates, dates after the corpus end (2024-12-30), and unparseable values.

No row, no participant or case id, and no restricted value with a count
is ever written; an unparseable value is quoted as an example only for a
column that is neither an identifier, restricted, nor a quasi-identifier.
"""

from __future__ import annotations

import difflib
from collections.abc import Iterable, Mapping, Sequence
from datetime import time
from pathlib import Path
from typing import Any

import polars as pl
import yaml

from judgemetrics.ingest.cook_sao.schema import (
    AGE_AT_INCIDENT,
    BLANKED_COLUMNS,
    CASE_ID,
    CHARGE_DISPOSITION,
    CHARGE_DISPOSITION_REASON,
    CHARGE_ID,
    CHARGE_VERSION_ID,
    CODED_COLUMNS,
    COVERAGE_END,
    COVERAGE_START,
    DATE_COLUMNS,
    DATE_FORMATS,
    IDENTIFIER_COLUMNS,
    JUDGE_COLUMNS,
    NUMERIC_COLUMNS,
    PARTICIPANT_ID,
    RECEIVED_DATE,
    RESTRICTED_COLUMNS,
    RESTRICTED_VALUE_COLUMNS,
    VERIFIED_HEADERS,
)
from judgemetrics.ingest.cook_sao.sources import DATASETS, SOURCE_ID
from judgemetrics.ingest.cook_sao.stored import LocalArtifact

PROFILE_VERSION = 1
PROFILE_PATH = Path("data") / "reference" / "cook_sao" / "profile.yaml"
HEADER = (
    "# data/reference/cook_sao/profile.yaml\n"
    "# The value-set profile of the five Cook County State's Attorney exports.\n"
    "# Generated by `judgemetrics sources profile cook_sao` from the stored artifacts\n"
    '# (docs/ARCHITECTURE.md "Cook County source"); regenerate it, never edit it by hand.\n'
    "# `--check` exits 1 when this file differs from the render. Race and gender are\n"
    "# listed as values only, the age as a range: no restricted value carries a count.\n"
)
CORPUS_END = COVERAGE_END
EARLIEST_EXPECTED_RECEIPT = COVERAGE_START
EXAMPLES = 5
SHARE_DIGITS = 6
CHARGE_DATASETS = ("initiation.csv", "dispositions.csv", "sentencing.csv")
INTAKE = "intake.csv"
DISPOSITION_DATASETS = ("dispositions.csv", "sentencing.csv")
_EXAMPLE_EXCLUDED = frozenset((*IDENTIFIER_COLUMNS, *BLANKED_COLUMNS))


class ProfileError(Exception):
    """An export cannot be profiled (header drift, unreadable file)."""


# --- scanning ------------------------------------------------------------------------


def scan(artifact: LocalArtifact) -> pl.LazyFrame:
    """The export as strings, an empty field (quoted or not) null, header verified."""
    verified = VERIFIED_HEADERS[artifact.external_id]
    frame = pl.scan_csv(artifact.path, infer_schema=False, encoding="utf8")
    headers = tuple(frame.collect_schema().names())
    if headers != verified:
        missing = [h for h in verified if h not in headers]
        extra = [h for h in headers if h not in verified]
        msg = (
            f"{artifact.external_id}: the header differs from the verified set "
            f"(missing {missing}, extra {extra})"
        )
        raise ProfileError(msg)
    return frame.with_columns(
        pl.when(pl.col(name) == "").then(None).otherwise(pl.col(name)).alias(name)
        for name in headers
    )


def _collect(frame: pl.LazyFrame) -> pl.DataFrame:
    return frame.collect(engine="streaming")


def parsed_date(name: str) -> pl.Expr:
    """The column as a datetime under either of the exports' formats (null when neither)."""
    return pl.coalesce(
        pl.col(name).str.strptime(pl.Datetime("us"), fmt, strict=False) for fmt in DATE_FORMATS
    )


def parsed_number(name: str) -> pl.Expr:
    return pl.col(name).cast(pl.Float64, strict=False)


def _number(value: float | None) -> int | float | None:
    if value is None:
        return None
    return int(value) if float(value).is_integer() else float(value)


def _iso(value: Any) -> str | None:
    return None if value is None else value.date().isoformat()


def _counted(rows: Iterable[tuple[Any, int]]) -> list[list[Any]]:
    """``[[value, count], …]`` by count descending, then value."""
    return [[value, count] for value, count in sorted(rows, key=lambda r: (-r[1], str(r[0])))]


def _histogram(series: pl.Series) -> list[list[int]]:
    """``[[k, how many have k], …]`` by k."""
    counts = series.value_counts()
    return sorted([int(k), int(n)] for k, n in counts.iter_rows())


def value_counts(frame: pl.LazyFrame, name: str) -> list[list[Any]]:
    rows = _collect(
        frame.select(name).drop_nulls().group_by(name).agg(pl.len().alias("n"))
    ).iter_rows()
    return _counted((value, int(n)) for value, n in rows)


def _share(found: int, total: int) -> float:
    return round(found / total, SHARE_DIGITS) if total else 0.0


# --- per dataset ---------------------------------------------------------------------


def _column_stats(frame: pl.LazyFrame, headers: Sequence[str]) -> dict[str, dict[str, Any]]:
    """Nulls, distinct counts, date and numeric ranges, and parse failures in one scan."""
    exprs: list[pl.Expr] = [pl.len().alias("__rows")]
    for name in headers:
        exprs.append(pl.col(name).is_null().sum().alias(f"{name}|nulls"))
        if name not in RESTRICTED_COLUMNS:
            exprs.append(pl.col(name).drop_nulls().n_unique().alias(f"{name}|distinct"))
        if name in DATE_COLUMNS:
            parsed = parsed_date(name)
            exprs += [
                pl.col(name).str.contains(pattern).sum().alias(f"{name}|format|{fmt}")
                for fmt, pattern in DATE_FORMATS.items()
            ]
            exprs += [
                parsed.min().alias(f"{name}|min"),
                parsed.max().alias(f"{name}|max"),
                (pl.col(name).is_not_null() & parsed.is_null()).sum().alias(f"{name}|unparseable"),
                (parsed.dt.time() != time(0)).sum().alias(f"{name}|not_midnight"),
            ]
        elif name in NUMERIC_COLUMNS:
            number = parsed_number(name)
            exprs.append(
                (pl.col(name).is_not_null() & number.is_null()).sum().alias(f"{name}|unparseable")
            )
            if name not in IDENTIFIER_COLUMNS:
                exprs += [number.min().alias(f"{name}|min"), number.max().alias(f"{name}|max")]
    row = _collect(frame.select(exprs)).row(0, named=True)
    stats: dict[str, dict[str, Any]] = {"__rows": {"rows": int(row["__rows"])}}
    for name in headers:
        entry: dict[str, Any] = {"nulls": int(row[f"{name}|nulls"])}
        if name in RESTRICTED_VALUE_COLUMNS:
            entry = {}  # values only, added by the caller
        if f"{name}|distinct" in row:
            entry["distinct"] = int(row[f"{name}|distinct"])
        if name in DATE_COLUMNS:
            entry["formats"] = {fmt: int(row[f"{name}|format|{fmt}"] or 0) for fmt in DATE_FORMATS}
            entry["min"] = _iso(row[f"{name}|min"])
            entry["max"] = _iso(row[f"{name}|max"])
            entry["unparseable"] = int(row[f"{name}|unparseable"])
            entry["not_midnight"] = int(row[f"{name}|not_midnight"])
        elif name in NUMERIC_COLUMNS:
            entry["unparseable"] = int(row[f"{name}|unparseable"])
            if f"{name}|min" in row:
                entry["min"] = _number(row[f"{name}|min"])
                entry["max"] = _number(row[f"{name}|max"])
        stats[name] = entry
    return stats


def profile_dataset(artifact: LocalArtifact) -> dict[str, Any]:
    name = artifact.external_id
    frame = scan(artifact)
    headers = VERIFIED_HEADERS[name]
    stats = _column_stats(frame, headers)
    rows = stats.pop("__rows")["rows"]
    coded = set(CODED_COLUMNS[name])
    judge = JUDGE_COLUMNS.get(name)
    for column in headers:
        if column in coded or column == judge:
            stats[column]["values"] = value_counts(frame, column)
        elif column in RESTRICTED_VALUE_COLUMNS:
            values = _collect(frame.select(pl.col(column).drop_nulls().unique()))[column]
            stats[column] = {"values": sorted(values.to_list())}
        elif column == AGE_AT_INCIDENT:
            stats[column] = {
                key: stats[column][key] for key in ("nulls", "min", "max", "unparseable")
            }
    dataset: dict[str, Any] = {"rows": rows, "columns": stats}
    if name in DISPOSITION_DATASETS:
        pairs = _collect(
            frame.group_by(CHARGE_DISPOSITION, CHARGE_DISPOSITION_REASON).agg(pl.len().alias("n"))
        )
        dataset["disposition_reason_pairs"] = [
            [disposition, reason, int(n)]
            for disposition, reason, n in sorted(
                pairs.iter_rows(), key=lambda r: (-r[2], str(r[0]), str(r[1]))
            )
        ]
    return dataset


# --- keys ----------------------------------------------------------------------------


def _key_pairs(frame: pl.LazyFrame) -> pl.DataFrame:
    return _collect(frame.select(CASE_ID, PARTICIPANT_ID).drop_nulls().unique())


def _keys(
    artifact: LocalArtifact, frame: pl.LazyFrame, intake_pairs: pl.DataFrame
) -> dict[str, Any]:
    name = artifact.external_id
    pairs = _key_pairs(frame)
    per_participant = pairs.group_by(PARTICIPANT_ID).agg(pl.col(CASE_ID).n_unique().alias("n"))
    per_case = pairs.group_by(CASE_ID).agg(pl.col(PARTICIPANT_ID).n_unique().alias("n"))
    keys: dict[str, Any] = {
        "cases": pairs[CASE_ID].n_unique(),
        "participants": pairs[PARTICIPANT_ID].n_unique(),
        "case_participants": pairs.height,
        "participants_in_more_than_one_case": int((per_participant["n"] > 1).sum()),
        "participants_per_case": _histogram(per_case["n"]),
    }
    if name != INTAKE:
        found = pairs.join(intake_pairs, on=[CASE_ID, PARTICIPANT_ID], how="semi").height
        moved = pairs.join(intake_pairs, on=PARTICIPANT_ID, how="inner", suffix="_intake").filter(
            pl.col(CASE_ID) != pl.col(f"{CASE_ID}_intake")
        )
        cases_found = (
            pairs.select(CASE_ID)
            .unique()
            .join(intake_pairs.select(CASE_ID).unique(), on=CASE_ID, how="semi")
            .height
        )
        keys["in_intake"] = {
            "case_participants_found": found,
            "case_participants_share": _share(found, pairs.height),
            "cases_found": cases_found,
            "cases_share": _share(cases_found, keys["cases"]),
            "participants_under_another_case": moved[PARTICIPANT_ID].n_unique(),
        }
    if name in CHARGE_DATASETS:
        keys["charges"] = _charge_keys(name, frame)
    return keys


def _charge_keys(name: str, frame: pl.LazyFrame) -> dict[str, Any]:
    rows = _collect(
        frame.select(CASE_ID, PARTICIPANT_ID, CHARGE_ID, CHARGE_VERSION_ID).filter(
            pl.col(CHARGE_ID).is_not_null()
        )
    )
    by_charge = rows.group_by(CHARGE_ID).agg(
        pl.col(CHARGE_VERSION_ID).drop_nulls().n_unique().alias("versions"),
        pl.col(CASE_ID).drop_nulls().n_unique().alias("cases"),
    )
    by_version = (
        rows.filter(pl.col(CHARGE_VERSION_ID).is_not_null())
        .group_by(CHARGE_VERSION_ID)
        .agg(
            pl.len().alias("rows"),
            pl.col(PARTICIPANT_ID).drop_nulls().n_unique().alias("participants"),
            pl.col(CHARGE_ID).n_unique().alias("charges"),
        )
    )
    charges: dict[str, Any] = {
        "rows_with_charge_id": rows.height,
        "charge_ids": by_charge.height,
        "charge_versions": by_version.height,
        "charge_ids_in_more_than_one_case": int((by_charge["cases"] > 1).sum()),
        "versions_per_charge": _histogram(by_charge["versions"]),
        "versions_in_more_than_one_charge": int((by_version["charges"] > 1).sum()),
        "rows_per_charge_version": _histogram(by_version["rows"]),
    }
    if name == "initiation.csv":
        charges["participants_per_charge_version"] = _histogram(by_version["participants"])
        charges["versions_with_more_than_one_participant"] = int(
            (by_version["participants"] > 1).sum()
        )
    else:
        per_participant = rows.group_by(PARTICIPANT_ID).agg(pl.len().alias("rows"))
        charges["rows_per_participant"] = _histogram(per_participant["rows"])
    return charges


# --- anomalies -----------------------------------------------------------------------


def _anomalies(artifact: LocalArtifact, frame: pl.LazyFrame) -> dict[str, Any]:
    headers = VERIFIED_HEADERS[artifact.external_id]
    received = parsed_date(RECEIVED_DATE).dt.date()
    early = _collect(
        frame.select(received.alias("d"))
        .filter(pl.col("d") < EARLIEST_EXPECTED_RECEIPT)
        .group_by("d")
        .agg(pl.len().alias("n"))
    )
    anomalies: dict[str, Any] = {
        "received_before_2011": {
            "rows": int(early["n"].sum()),
            "earliest": [
                [day.isoformat(), int(n)] for day, n in sorted(early.iter_rows())[:EXAMPLES]
            ],
        }
    }
    late: dict[str, Any] = {}
    for column in headers:
        if column not in DATE_COLUMNS:
            continue
        after = _collect(
            frame.select(parsed_date(column).dt.date().alias("d"))
            .filter(pl.col("d") > CORPUS_END)
            .group_by("d")
            .agg(pl.len().alias("n"))
        )
        if after.height:
            entry: dict[str, Any] = {"rows": int(after["n"].sum())}
            if column not in BLANKED_COLUMNS:
                entry["latest"] = [
                    [day.isoformat(), int(n)]
                    for day, n in sorted(after.iter_rows(), reverse=True)[:EXAMPLES]
                ]
            late[column] = entry
    anomalies["dates_after_corpus_end"] = late
    unparseable: dict[str, Any] = {}
    for column in headers:
        if column in DATE_COLUMNS:
            failed = pl.col(column).is_not_null() & parsed_date(column).is_null()
        elif column in NUMERIC_COLUMNS:
            failed = pl.col(column).is_not_null() & parsed_number(column).is_null()
        else:
            continue
        values = _collect(
            frame.filter(failed).group_by(column).agg(pl.len().alias("n"))
        ).iter_rows()
        counted = _counted((value, int(n)) for value, n in values)
        if not counted:
            continue
        entry = {"rows": sum(n for _, n in counted)}
        if column not in _EXAMPLE_EXCLUDED:
            entry["examples"] = counted[:EXAMPLES]
        unparseable[column] = entry
    anomalies["unparseable"] = unparseable
    return anomalies


# --- the whole profile ----------------------------------------------------------------


def build_profile(artifacts: Sequence[LocalArtifact]) -> dict[str, Any]:
    """The profile mapping of the five artifacts (in ``sources.DATASETS`` order)."""
    expected = [dataset.external_id for dataset in DATASETS]
    if [artifact.external_id for artifact in artifacts] != expected:
        msg = f"expected the five artifacts {expected} in order"
        raise ProfileError(msg)
    frames = {artifact.external_id: scan(artifact) for artifact in artifacts}
    intake_pairs = _key_pairs(frames[INTAKE])
    datasets: dict[str, Any] = {}
    keys: dict[str, Any] = {}
    anomalies: dict[str, Any] = {}
    for artifact in artifacts:
        frame = frames[artifact.external_id]
        datasets[artifact.external_id] = profile_dataset(artifact)
        keys[artifact.external_id] = _keys(artifact, frame, intake_pairs)
        anomalies[artifact.external_id] = _anomalies(artifact, frame)
    return {
        "version": PROFILE_VERSION,
        "source": SOURCE_ID,
        "date_formats": list(DATE_FORMATS),
        "corpus_end": CORPUS_END.isoformat(),
        "artifacts": [
            {
                "external_id": artifact.external_id,
                "sha256": artifact.sha256,
                "bytes": artifact.size_bytes,
                "rows_updated_at": artifact.rows_updated_at,
                "retrieved_at": artifact.retrieved_at,
            }
            for artifact in artifacts
        ],
        "datasets": datasets,
        "keys": keys,
        "anomalies": anomalies,
    }


def render_profile(profile: Mapping[str, Any]) -> str:
    body = yaml.safe_dump(
        dict(profile),
        sort_keys=True,
        allow_unicode=True,
        default_flow_style=None,
        width=100,
    )
    return HEADER + body


def load_profile(path: Path) -> dict[str, Any]:
    """The committed profile (``yaml.safe_load``); a mapping with a ``version``."""
    try:
        document = yaml.safe_load(path.read_text(encoding="utf-8"))
    except (OSError, yaml.YAMLError) as exc:
        msg = f"cannot read the profile {path}: {exc}"
        raise ProfileError(msg) from exc
    if not isinstance(document, dict) or document.get("version") != PROFILE_VERSION:
        msg = f"{path} is not a version {PROFILE_VERSION} profile"
        raise ProfileError(msg)
    return document


def check_profile(path: Path, rendered: str) -> list[str]:
    """The unified diff between the file at ``path`` and the render; empty when equal."""
    try:
        current = path.read_bytes().decode("utf-8")
    except FileNotFoundError:
        return [f"--- {path} is missing", f"+++ render ({len(rendered.splitlines())} lines)"]
    if current == rendered:
        return []
    return list(
        difflib.unified_diff(
            current.splitlines(), rendered.splitlines(), fromfile=str(path), tofile="render"
        )
    )


def write_profile(path: Path, rendered: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(rendered.encode("utf-8"))
